:toc:
:toclevels: 5

= General Data Protection Regulation

Source: https://eur-lex.europa.eu/eli/reg/2016/679/oj[eur-lex.europa.eu]

[quote]
Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation)

[#art1]
== Article 1: Subject matter and objectives

The GDPR regulates the fundamental rights of *natural persons* regarding the protection and free movement of *personal data* throughout the European Union and European Economic Area.

[#art2]
== Article 2: Material scope

The GDPR applies to the *wholly or partly automated processing* of personal data, and to the *manual processing* of personal data that is part of a *<<filing-system,filing system>>*.

The GDPR _does not_ apply to the processing of personal data for purposes that are:

. outside the scope of *European Union law*
. in accordance with *Chapter 2 of Title V of the https://eur-lex.europa.eu/eli/treaty/teu_2012/oj[Treaty on European Union]* (General provisions on the Union's external action and specific provisions on the common foreign and security policy)
. *personal/household activities* carried out by a *natural person*
. required by *competent authorities* for the investigation and prevention of *criminal offenses* or to execute relevant penalties

The GDPR *does not affect* the application of the https://eur-lex.europa.eu/eli/dir/2000/31/oj[2000 directive on electronic commerce] (see Articles 12–15).

[#art3]
== Article 3: Territorial scope

The GDPR applies to:

. the processing of personal data by *controllers and processors* established in the European Union (_cf._ <<main-establishment,main establishment>>), *regardless of the actual location of processing*
. the processing of personal data by controllers and processors in any location where Member State law applies
. the processing of personal data of *data subjects in the European Union* by controllers and processors established elsewhere, if:
.. goods or services are being offered
.. subjects' behavior within the European Union is otherwise being monitored

[#art4]
== Article 4: Definitions

personal data::
any information relating to *an <<identifiable-natural-person,_identified or identifiable_ natural person*>> (the *data subject*)

[#identifiable-natural-person]
identifiable natural person::
a natural person who can be *directly or indirectly* identified through use of a name, ID, location data, or other identifier specific to the person (see also: <<genetic-data,genetic data>>).

[#processing]
processing::
any operation performed on personal data, regardless of whether it is automated; this includes collection, recording, structuring, *storage*, alteration, retrieval, and dissemination of personal data.

restriction of processing::
the marking of stored personal data so as to limit its future processing

[#profiling]
profiling::
automated processing of personal data to evaluate personal aspects of the data subject; this includes the analysis or prediction of the subject's performance, economic situation, health, interests, location, etc.

[#pseudonymization]
pseudonymization::
the processing of personal data in order to prevent identification of the respective data subject without additional information; said additional information must be *stored separately and adequately secured*

[#filing-system]
filing system::
a structured, accessible and identifiable set of personal data

[#art4-controller]
controller::
an entity which, _alone or jointly with others_, determines the *purposes and means* of the processing of personal data

[#art4-processor]
processor::
an entity which <<processing,processes>> personal data on behalf of a controller

recipient::
an entity to which personal data is provided; public authorities which receive personal data as part of an inquiry *are not considered recipients* but must comply with applicable data protection rules

[#third-party]
third party::
an entity other than the data subject, controller, or processor which is authorized to process personal data

[#consent]
consent::
*freely given, specific, informed and unambiguous* indication that the data subject agrees to have their personal data processed

CAUTION: Consent must be unambiguous; *silence, pre-ticked boxes or inactivity therefore do not constitute consent* (see Recital 32).

[#personal-data-breach]
personal data breach::
a breach of security leading to *the destruction, loss, alteration, unauthorized disclosure of or access to* processed personal data

[#genetic-data]
genetic data::
personal data relating to unique *inherited or acquired genetic characteristics* of a natural person, particularly that which results from an analysis of a biological sample

[#biometric-data]
biometric data::
personal data resulting from technical processing, relating to physical, physiological or behavioral characteristics of a natural person; this includes facial images or fingerprints

[#main-establishment]
main establishment (controllers)::
the establishment of the controller in the European Union where *the decisions on the purposes and means of processing* are made; by default, this is the place of central administration within the European Union

main establishment (processors)::
the establishment of the processor in the European Union where *the main processing activities* take place; by default, this is the place of central administration within the European Union

representative::
a natural or legal person established in the European Union who represents (see <<art27,Article 27>>) a controller or processor

enterprise::
a natural or legal person engaged in an economic activity; this includes partnerships or associations

[#group-of-undertakings]
group of undertakings::
a controlling *undertaking* and its controlled undertakings
footnote:[https://uk.practicallaw.thomsonreuters.com/w-014-8183[Practical Law: group of undertakings]]

binding corporate rules::
data protection policies which are followed by a controller or processor established in a Member State for *transfers of personal data to a controller or processor in a third country* within a group of undertakings (see also <<art47,Article 47>>).

supervisory authority::
see <<art51,Article 51>>

[#supervisory-authority-concerned]
supervisory authority concerned::
a supervisory authority *concerned by* the processing of personal data because:

. the controller or processor is established on the territory of the supervisory authority's Member State
. data subjects in said Member State are (likely to be) substantially affected by said processing
. a <<art77,complaint has been filed>> with the supervisory authority

cross-border processing::
personal data processing that involves data subjects or controllers/processors in multiple Member States

relevant and reasoned objection::
an objection regarding whether the GDPR has been infringed upon

[#information-society-service]
information society service::
a paid service provided electronically, upon request by the recipient, for the processing and storage of data (see Article 1(1) of https://eur-lex.europa.eu/eli/dir/2015/1535/oj[Directive (EU) 2015/1535])

international organization::
an organization and its subordinates governed by international law

[#art5]
== Article 5: Principles relating to processing of personal data

The controller is responsible ("accountability") for ensuring that personal data is:

. *lawfully, fairly and transparently* processed ("lawfulness, fairness and transparency").
. collected for *specific, explicit and legitimate* purposes
. *relevant* and *limited* to the specified purpose ("data minimization")
. accurate and kept up to date; inaccurate personal data *must be erased or updated without delay* ("accuracy")
. suitably anonymized; data subjects *must not be identifiable for longer than necessary*
.. Personal data may be archived for longer periods *in the public interest or for research purposes* (see <<art89,Article 89>>) with the appropriate privacy safeguards
. *appropriately secured*; this includes protection against unauthorized access and data loss, destruction or other
damage ("integrity and confidentiality")

[#art6]
== Article 6: Lawfulness of processing

Data processing is *lawful* if at least one of the following applies:

. the data subject has given <<consent,consent>> to the processing of their personal data for a specific purpose
. processing is necessary to *fulfill a contract* with the data subject
. processing is *requested by the data subject* prior to entering into a contract
. processing is necessary to comply with the controller's *legal obligations* footnoteref:[art6-2,The conditions for such processing are specified by European Union law; Member States may introduce more specific requirements.]
. processing is necessary to protect the *vital interests of the data subject*
. processing is necessary to carry out an action *in the public interest* footnoteref:[art6-2]
. processing is necessary to *exercise an official authority* of the controller footnoteref:[art6-2]
[#art6-interests]
. processing is necessary to pursue the interests of the controller or of a third party, given that these interests do not infringe on the fundamental rights of the data subject, *in particular when the data subject is a child*.
.. This does not apply to processing carried out by public authorities.

If data processing occurs for purposes other than that for which the personal data was initially collected, and *is not based on consent of the data subject* or on European Union or Member State law, the controller *must take into account* (among other things) the following, in order to determine whether the processing is compatible:

. any link between *the initial purpose* and the intended further processing
. the context of the data collection
. whether *"special personal data"* (see <<art9, Article 9>>) is processed
. whether personal data related to criminal convictions or offenses (see <<art10,Article 10>>) is processed
. *any possible consequences* of the intended further processing
. *any appropriate safeguards*; this includes *encryption* or *<<pseudonymization,pseudonymization>>*

[#art7]
== Article 7: Conditions for consent

If the lawfulness of data processing is *<<art6,based on consent>>*, the controller *must be able to clearly demonstrate* that the data subject has freely consented to the processing of their personal data. Data subjects must be *clearly informed* when consent is required, and *must be allowed to withdraw their consent* at any time; withdrawal *must not be made any more difficult* than the initial request for consent.

Consent should not be "bundled up as a condition of service", unless it is *absolutely necessary* footnote:[https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/consent/what-is-valid-consent[UK Information Commissioner's Office: What is valid consent?]]; if consent is required as part of the conditions for a contract, but *is not absolutely necessary* for its fulfillment, it is *not considered freely given*.

[#art8]
== Article 8: Conditions applicable to child's consent in relation to information society services

_See also <<information-society-service,information society services>>._

If the data subject is a child, and has consented to the processing of their personal data, said processing is legal if:

. the data subject is at least 16 years old; Member States may provide lower ages, *provided that said age is not below 13 years*.
. consent has been given by the child's legal guardian
.. The controller must *make reasonable efforts* to verify that any given consent has been properly authorized.

[#art9]
== Article 9: Processing of special categories of personal data

Processing of personal data concerning:

. racial or ethnic origin
. political opinions
. religious or philosophical beliefs
. trade union membership
. <<genetic-data,genetic>>, <<biometric-data,biometric>> and health data *for the purpose of identifying a natural person*
. a natural person's *sex life or sexual orientation*

*is prohibited*, unless at least one of the following applies:

[#art9-exceptions]
. the data subject has *explicitly given consent*, unless European Union or Member State law otherwise dictate that *the prohibition may not be lifted*
. processing is necessary to carry out the obligations or execute specific rights of the controller or data subject related to *employment or social security and social protection law*, provided that it is authorized by European Union or Member State law, or by a *https://en.wikipedia.org/wiki/Collective_agreement[collective agreement]* in accordance with Member State law
. processing is necessary *to protect the <<art6,vital interests>>* of the data subject
. processing is carried out, with the appropriate safeguards, *as part of a non-profit organization's legitimate activities*, provided that the processing relates *only to the current or former members* of the organization, or to members that have *regular contact* with it; personal data must not be disclosed outside the scope of said organization without the consent of the data subject
. processing relates to personal data that is *in the public domain* (has been manifestly made public by the data subject)
. processing is necessary for *the establishment, exercise or defense of legal claims*, or when a court acts in its judicial capacity
. processing is *in the public interest*, with the appropriate safeguards, in accordance with European Union or Member State law
. processing is necessary for the purposes of *preventive or occupational medicine*, provided that the professional is *subject to confidentiality* (professional secrecy) under European Union or Member State law, or *rules established by national competent bodies*
. processing is necessary for archiving or for research purposes, with the appropriate safeguards

Member States may introduce more specific restrictions regarding the processing of <<genetic-data,genetic>>, <<biometric-data,biometric>> and health data.

[#art10]
== Article 10: Processing of personal data relating to criminal convictions and offenses

Processing of personal data relating to criminal convictions and offenses may only be carried out *with the appropriate safeguards*, and must occur *under the control of an official authority*, or when it is otherwise authorized by European Union or Member State law.

[#art11]
== Article 11: Processing which does not require identification

If a controller does not require the identification of a data subject, they are *not required* to maintain or process additional information in order to identify the data subject to comply with the GDPR.

[#art11-2]
If a controller demonstrably is not in a position to be able to identify the data subject, they must attempt to inform the data subject of this; Articles <<art16,16>>, <<art17,17>>, <<art18,18>>, <<art19,19>> and <<art20,20>> do not apply in such a situation, *unless the data subject provides additional identifying information* in order to exercise their rights under said articles.

[#art12]
== Article 12: Transparent information, communication and modalities for the exercise of the rights of the data subject

All processed personal data referred to by Articles <<art13,13>>, <<art14,14>>, <<art15,15>>, <<art16,16>>, <<art17,17>>, <<art18,18>>, <<art19,19>>, <<art20,20>>, <<art21,21>>, <<art22,22>> and <<art34,34>> must be provided (in writing, orally, or by other means) to the data subject in a *concise, transparent, intelligible and easily accessible form*, particularly for *any information addressed to a child*. Controllers must facilitate the exercise of data subjects' rights according to Articles 15–22, unless they <<art11-2,demonstrably cannot identify the data subject>>.

A standardized set of *icons* may be used to *clearly and visibly present* the required information; the European Commission may adopt delegated acts (see <<art92,Article 92>>) to determine the procedures for providing said standardized icons.

Controllers must provide information on the status of <<art15,requests made unter Articles 15–22>> *without undue delay*; this must occur *within one month* of the receipt of the request. If the controller does not take action, they must likewise notify the data subject within one month and inform them of the *reasons for not taking action* and of any possible *legal remedies*.

[#art12-fee]
Any information provided and actions taken under the aforementioned articles must be available *free of charge*, unless the requests are demonstrated to be manifestly *unfounded or excessive* (i.e. repetitive), the controller may charge *a reasonable fee* or refuse to act on the request. If the controller has *reasonable doubts* about the identity of the requester, they may *request additional information*.

[#art13]
== Article 13: Information to be provided where personal data are collected from the data subject

When personal data is obtained, if they have not already done so, the controller must provide the following information:

. the *identity and contact details of the controller*, and, if applicable, of its representative
. the contact details of the *<<art37,data protection officer>>*, if applicable
. the *<<art5,purposes>> and <<art6,legal basis>> of the processing*
. the *<<art6-interests,legitimate interests>>* of the controller or of a <<third-party,third party>>
. where applicable, *any intention by the controller to transfer personal data to a third country or international organization* and of any relevant <<art45,adequacy decision>>, or in the case of transfers to which Articles <<art46,46>>, <<art47,47>> and <<art49,49>>, *a reference to the appropriate safeguards*.
. how long the personal data will be stored
. the rights of the data subject to *submit an <<art15,information>>, <<art16,rectification>> or <<art17,erasure request>>*, to *<<art18,restriction of processing>>* and *<<art20,data portability>>*,footnoteref:[ico-portability, https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/right-to-data-portability[UK Information Commissioner’s Office: Right to data portability] ] and to *withdraw consent or <<art21,object to processing>>* at any time; withdrawal of consent does not affect the lawfulness of processing prior to the withdrawal
. the right to file a complaint with a <<supervisory-authority,supervisory authority>> (see <<art77,Article 77>>)
. *whether the acquisition of personal data is a contractual requirement*, and the consequences if it is not provided
. whether the controller intends to further process the personal data <<art5,for another purpose>>

[#art14]
== Article 14: Information to be provided where personal data have not been obtained from the data subject

When personal data has been obtained from a source other than the data subject, if they have not already done so, the controller must provide the following information:

. the *identity and contact details of the controller*, and, if applicable, of its representative
. the contact details of the *<<art37,data protection officer>>*, if applicable
. the *<<art5,purposes>> and <<art6,legal basis>> of the processing*
. the categories of the personal data
. the recipients of the personal data, if applicable
. where applicable, *any intention by the controller to transfer personal data to a third country or international organization* and of any relevant <<art45,adequacy decision>>, or in the case of transfers to which Articles <<art46,46>>, <<art47,47>> and <<art49,49>>, *a reference to the appropriate safeguards*.
. how long the personal data will be stored
. the *<<art6-interests,legitimate interests>>* of the controller or of a <<third-party,third party>>
. the rights of the data subject to *submit an <<art15,information>>, <<art16,rectification>> or <<art17,erasure request>>*, to *<<art18,restriction of processing>>* and *<<art20,data portability>>*,footnoteref:[ico-portability]
. the right to file a complaint with a <<supervisory-authority,supervisory authority>> (see <<art77,Article 77>>)
. *the source of the personal data*, and whether it came from publicly accessible sources
. *whether <<profiling,profiling>>, automated processing or decision-making is involved* (see Article <<art22,22>>), and, if applicable, information about its operation and possible consequences
. whether the controller intends to further process the personal data <<art5,for another purpose>>

Controllers must provide data subjects with this information *without undue delay*; this must occur *within one month* of the processing of the personal data, unless:

. informing the data subject would be *impossible, or involve a disproportionate effort*, *especially for archival or research purposes*; in these cases, the controller must ensure the data subjects' rights and freedoms are protected appropriately, including *making the information publicly available*.
. obtaining or disclosure is *explicitly laid down by European Union or Member State law*
. the personal data <<art90,must remain confidential>>

[#art15]
== Article 15: Right of access by the data subject

If requested, the controller *must inform the data subject* whether any personal data has been processed, and, if applicable, provide access to said data and the following additional information:

. the *<<art5,purpose>> of the processing*
. the categories of the personal data
. the recipients of the personal data, if applicable, especially those which are *international organizations* or are *located in third countries*
. how long the personal data will be stored
. the rights of the data subject to *submit a <<art16,rectification>> or <<art17,erasure request>>* and to *<<art18,restriction of processing>>*
. the right to file a complaint with a <<supervisory-authority,supervisory authority>> (see <<art77,Article 77>>)
. *the source of the personal data*, and whether it came from publicly accessible sources, if <<art14,the data was not collected from the data subject>>
. *whether <<profiling,profiling>>, automated processing or decision-making is involved* (see Article <<art22,22>>), and, if applicable, information about its operation and possible consequences
. *what safeguards are in place to protect the <<art5,integrity and confidentiality>> of personal data*, if it has been transferred to a third country or to an international organization

The controller must also <<art12-fee,provide a copy of the processed personal data>>;
the right to obtain a copy *must not adversely affect the rights and freedoms of others*.

[#art16]
== Article 16: Right to rectification

The data subject has the right to request *rectification of personal data* and to *have incomplete personal data completed*, from the controller, without undue delay.

[#art17]
== Article 17: Right to erasure ("right to be forgotten")

The data subject has the right to request *erasure of personal data* from the controller without undue delay; additionally, the controller is required to erase personal data without undue delay when:

. the personal data is no longer necessary
. the data subject *withdraws consent* (see Articles <<art6,6>>, <<art9,9>> and <<art13,13>>)
. the data subject <<art21,objects to processing>>
. the personal data *has been unlawfully processed*
. the personal data must be erased to comply with European Union or Member State law

If the personal data has been made public by the controller, and is obliged by the aforementioned conditions to erase the data, the controller *must make a reasonable effort* to <<art19,inform other controllers>> which are processing said data that the data subject has requested its erasure.

These conditions *do not apply* if:

. processising is necessary to exercise *<<art85,the right to freedom of expression and information>>*
. processing is necessary to *comply with legal obligations*, to *exercise an official authority* of the controller, or for a task *carried out in the public interest* (see <<art9-exceptions,Article 9>>)
. processing is necessary for archiving or for research purposes
. processing is necessary for *the establishment, exercise or defense of legal claims*

[#art18]
== Article 18: Restriction of processing

Restriction of processing is an alternative to <<art17,erasure>>; the data subject has the right to limit how their data is processed by requesting *restriction of processing* from the controller, provided that one of the following applies:

. the accuracy of the personal data is contested by the data subject, enabling the controller to verify its accuracy
. the processing is unlawful, but the data subject *objects to its erasure* and requests restriction of processing instead
. the personal data is no longer necessary for the controller, but it is required by the data subject for *the establishment, exercise or defense of legal claims*
. the data subject <<art21,objects to processing>>

If processing of personal data has been restricted, said data may only be processed *with the consent of the data subject*, for *the establishment, exercise or defense of legal claims*, for the protection of the rights of another natural or legal person, or for purposes that are in the public interest.

The data subject must be informed by the controller prior to the lifting of restriction of processing.

[#art19]
== Article 19: Notification obligation regarding rectification or erasure of personal data or restriction of processing

The controller must inform *all recipients of personal data* of any relevant <<art16,rectification>>, <<art17,erasure>>, or <<art18,restriction of processing>> requests made by the data subject. If the data subject requests it, they must additionally inform the data subject about said recipients.

[#art20]
== Article 20: Right to data portability

The data subject has the right to *obtain the personal data* they have provided to a controller, and have it *freely transferred to another controller*, provided that:

. the processing is <<art6,based on consent or on a contract>> to which the data subject is a party
. the data processing is automated

The right to data portability *<<art15,must not adversely affect the rights and freedoms of others>>*.

[#art21]
== Article 21: Right to object

The data subject has the right to *object to processing* which is *"carried out in the public interest" or for the purposes of the controller's legitimate interests* <<art6,as specified in Article 6>>; the controller must cease processing of personal data unless it can demonstrate *compelling legitimate grounds* for the processing which override the rights and freedoms of the data subject.

If personal data is processed for _direct marketing_, the data subject may object to processing of all related personal data, *including <<profiling,profiling>>*; the controller must then stop *all processing of said personal data* for direct marketing purposes.

If personal data is processed for *research purposes*, the data subject may object to processing unless it is a necessary task *carried out in the public interest*.

These rights must be *explicitly brought to the attention of the data subject* and must be displayed *clearly and separately* from any other information.

Data subjects may exercise their right to object by automated means (see <<information-society-service,information society services>>).

[#art22]
== Article 22: Automated individual decision-making, including profiling

The data subject has the right to not be subject to *decisions based solely on automatic processing* that significantly affect them (including <<profiling,profiling>>), unless:

. the decision is *necessary for the fulfillment of a contract* between the data subject and the controller
. the decision is *authorized by European Union or Member State law*
. the automatic processing is based on the data subject's <<art6,explicit consent>>

given that these decisions are *not based on <<art9, special categories>> of personal data* and that
*sufficient safeguards are in place* to protect the data subject's rights, freedoms and legitimate interests.

[#art23]
== Article 23: Restrictions

European Union or Member State law may restrict the scope of any obligations and rights provided by Articles <<art5,5>>, <<art12,12>>, <<art13,13>>, <<art14,14>>, <<art15,15>>, <<art16,16>>, <<art17,17>>, <<art18,18>>, <<art19,19>>, <<art20,20>>, <<art21,21>>, <<art22,22>> and <<art34,34>> when such a restriction is necessary to safeguard:

. *national and public security*
. defense
. the investigation, detection and prevention of *criminal offenses and breaches of ethics* and the execution of relevant penalties
. important objectives of *general public interest to the European Union or a Member State*; this includes, among others, economic or financial interests, public health and social security
. the *protection of judicial independence* and legal proceedings
. a regulatory function connected to an official authority
. *the protection of the data subject*, or of the rights and freedoms of others
. the enforcement of civil law claims

All such legislation must include:

. the *<<art5,purpose>> of the processing*
. the categories of the personal data
. the *scope of the introduced restrictions*
. any safeguards in place to *prevent unlawful access* to the personal data
. the specification of the controller(s)
. how long the personal data will be stored
. any risks to the rights of data subjects
. the right of data subjects to be informed about said restriction, *unless this would be detrimental to the effectiveness of the restriction*

[#art24]
== Article 24: Responsibilities of the controller

*The controller is responsible for taking steps to appropriately ensure that all processing is performed in accordance with the GDPR*; this includes the application of appropriate data protection policies.

Adherence to <<art40,approved codes of conduct>> or <<art42,approved certification mechanisms>> may be used to demonstrate Regulation compliance.

[#art25]
== Article 25: Data protection by design and by default

[quote,Article 25]
____
Taking into account the state of the art, the cost of implementation and the nature, scope, context and purposes of processing as well as the risks ... for rights and freedoms of natural persons posed by the processing, *the controller shall ... implement appropriate ... measures, such as pseudonymisation, which are designed to implement data-protection principles, such as data minimisation, in an effective manner* ... in order to meet the requirements of this Regulation and protect the rights of data subjects.

The controller shall implement appropriate ... measures for ensuring that, by default, only personal data which are *necessary for each specific purpose of the processing* are processed. That obligation applies to the amount of personal data collected, the extent of their processing, the period of their storage and their accessibility. In particular, *such measures shall ensure that by default personal data are not made accessible without the individual's intervention* to an indefinite number of natural persons.
____

Approved <<art42,certification mechanisms>> may be used to demonstrate Regulation compliance.

[#art26]
== Article 26: Joint controllers

Multiple controllers that jointly determine the purposes and means of processing are considered *<<art4-controller,joint controllers>>*. They must determine *their respective responsibilities* for compliance with the GDPR, especially regarding *the rights of the data subject under Articles <<art13,13>> and <<art14,14>>*.

Data subjects may exercise their rights in respect of and against each joint controller individually.

[#art27]
== Article 27: Representatives of controllers or processors not established in the Union

Controllers and processors established outside the European Union to which <<art3,Article 3>> applies *must designate a representative within the European Union*, unless processing is not regular, does not involve <<art9,special categories>> of data or <<art10,data relating to criminal convictions and offenses>>, is unlikely to be a risk to the rights of natural persons, or is carried out by a public authority. The representative *must be established in one of the Member States where data subjects are located*, and must be *mandated by the controller or processor* to be addressed in addition to *or instead of* the controller or processor by <<supervisory-authority,supervisory authorities>> and data subjects.

[#art28]
== Article 28: Processor

_See also <<art4-processor,processor>> (<<art4,Article 4>>)._

Controllers must only make use of processors that provide *sufficient guarantees* that processing will meet the requirements of the GDPR and protect the rights of the data subject.

Processors *may not delegate processing to another processor* without the authorization of the responsible controller.

Processing of personal data by a processor is governed by a binding, written contract between the controller and processor, or between a processor and a subordinate processor, that specifies the *purpose and means of the processing*; such a contract must specify that the processor shall:

. process personal data *only when instructed to do so by the controller*, unless required to do so by European Union or Member State law
. ensure that persons authorized to process the data *have committed themselves to confidentiality*
. *appropriately assist the controller with responding to requests for exercising the data subject's rights* (see Articles <<art15,15>>, <<art16,16>>, <<art17,17>>, <<art18,18>>, <<art19,19>>, <<art20,20>>, <<art21,21>> and <<art22,22>>) and with compliance with Articles <<art32,32>>, <<art33,33>>, <<art34,34>>, <<art35,35>> and <<art36,36>>
. *delete or return all personal data to the controller* when processing is no longer required, if requested by the controller, and deletes any existing copies unless European Union or Member State law requires said copies to be retained
. *make all information necessary to demonstrate GDPR compliance available* to the controller
. *allow for and contribute to audits* conducted by the controller or by a third party
. immediately inform the controller *if an instruction violates the GDPR* or other European Union or Member State law

Adherence to <<art40,approved codes of conduct>> or <<art42,approved certification mechanisms>> may be used to demonstrate Regulation compliance.

[#art28-standard-clauses]
The European Commission or a <<supervisory-authority,supervisory authority>> may offer or adopt *standard contractual clauses* footnote:[https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/standard-contractual-clauses-scc_en[European Commission: Standard Contractual Clauses]] that can be used as a basis for a contract between the controller and processor.

*If a processor violates the GDPR by determining the purposes and/or means of processing, it is considered a controller for the purposes of that processing*.

[#art29]
== Article 29: Processing under the authority of the controller or processor

Any authorized entity that has access to personal data may not process it *unless instructed to do so by the controller*, or if required to do so by European Union or Member State law.

[#art30]
== Article 30: Records of processing activities

CAUTION: The following obligations apply only to *organizations employing at least 250 persons*, unless processing occurs regularly, involves <<art9,special categories>> of data or <<art10,data relating to criminal convictions and offenses>>, or is likely to be a risk to the rights of data subjects.

Controllers and their respective representatives must maintain *written electronic records* of processing activities carried out as part of its operations, which must contain:

. the *identity and contact details of the controller*, and, if applicable, of its representative or <<art26,joint controller>>
. the contact details of the *<<art37,data protection officer>>*, if applicable
. the *<<art5,purposes>> of the processing*
. the categories of the personal data
. *any transfers of personal data to a third country or international organization* and any suitable safeguards
. any time limits for erasure of the stored data
. a description of technical and organizational security measures (see <<art32,Article 32>>)

Processors and their respective representatives must maintain *written electronic records* of processing activities carried out on behalf of a controller, which must contain:

. the *identity and contact details of the processor and controller(s)*, and, if applicable, of the controller's and/or processor's representative
. the contact details of the *<<art37,data protection officer>>*, if applicable
. the categories of processing carried out on behalf of each controller
. *any transfers of personal data to a third country or international organization* and any suitable safeguards
. a description of technical and organizational security measures (see <<art32,Article 32>>)

These records must be made available to the <<supervisory-authority,supervisory authority>> upon request.

[#art31]
== Article 31: Cooperation with the supervisory authority

The controller, processor, and their respective representatives must cooperate with the <<supervisory-authority,supervisory authority>>.

[#art32]
== Article 32: Security of processing

_See also Articles <<art6,6>>, <<art28,28>> and <<art25,25>>._

Controllers and processors must implement appropriate *technical and organizational security measures* to ensure an appropriate level of security, including but not limited to:

. the <<pseudonymization,pseudonymization>> and encryption of personal data
. insurance of the *<<art5,confidentiality, integrity, availability>> and resilience* of processing systems
. *restoration of availability* and access to personal data in the event of a technical incident
. regularly testing and evaluating the effectiveness of security measures

The risks presented by data processing should be taken into account when determining an appropriate level of security; these include *accidental or unlawful destruction, loss, alteration, unauthorised disclosure of, or access to personal data* (_cf._ <<personal-data-breach,personal data breach>>).

Adherence to <<art40,approved codes of conduct>> or <<art42,approved certification mechanisms>> may be used to demonstrate Regulation compliance.

[#art33]
== Article 33: Notification of a personal data breach to the supervisory authority

In the event of a <<personal-data-breach,personal data breach>>, the controller *must notify the <<supervisory-authority,supervisory authority>>, without undue delay* (within 72 hours after discovery) in accordance with <<art55,Article 55>>, of the following, unless the data breach is *unlikely to result in a risk to the rights of affected data subjects*:

. *the nature of the personal data breach*, including the categories & number of data subjects, and categories & number of personal data records, affected.
. *the contact details of the <<art37,data protection officer>>*, or other contact information where more information is available
. any likely consequences of the data breach
. any measures taken or to be taken by the controller to address the data breach

This information must be documented to verify Regulation compliance.

If it is not possible to provide all information at once, *it may be provided in phases without undue further delay*.

Processors must notify their respective controller *without undue delay* after discovering a data breach.

[#art34]
== Article 34: Communication of a personal data breach to the data subject

If a personal data breach *is likely to result in a high risk to the rights of affected data subjects*, the controller must inform affected data subjects *without undue delay*, using *clear and plain language*, containing all information as specified in <<art33,Article 33>>, excepting the nature of the data breach itself.

The data subject is not required to be informed of a data breach if at least one of the following applies:

. the controller has employed appropriate techniques to ensure that unauthorized reading of the affected data is impossible (e.g. encryption)
. the controller has ensured that the aforementioned "high risk" is no longer present
. informing the data subject would involve a disproportionate effort; in this case, a more effective mode of communication may be used

[#art35]
== Article 35: Data protection impact assessment

. In case new technologies are used in processing, an assessment has to be carried out to evaluate the possible protection of personal data.
. Assessments should be carried out with help of the data protection officer, where designated.
. This is specifically needed in case of:
.. evaluations of personal aspects of a natural person, used for processing (and profiling), which produce legal effects or similarly significantly affects to the person.
.. processing on a large scale of special categories of data <<art9,Article 9(1)>> or personal data relating to criminal convictions and offences <<art10,Article 10>>  
.. large scale systematic monitoring of a public area
. The Assessment has to contain at least:
.. a description of the processing operations
.. the <<art5,purposes>> of the processing, inluding, where applicable, the interest of the controller
.. an assessment of :
... the neccessity and proportionality of the processing in relation to the <<art5,purposes>>.
... the risks to the rights and freedoms of data subjects, see paragraph 1
. Compliance with the approved codes of conduct referred in <<art40,Article 40>> shall be taken into account by both the controllers and processors
. Where appropriate, the controller shall seek the opinon of the data subject, without prejudice to the protection of their own interest or the security of processing operations.
. The supervisory authority shall release a list of:
.. the kind of processing operations which require the impact assessment
.. may also release a list of operations where no data protection impact assessment is required.
.. both should be communiated the the Board <<art68,Article 68>>
.. prior to the lists referred above, lists where goods or services are offered, data subjects behaviour is monitored, or the free movement of personal data in the Union is affected, shall apply the consistency mechanism referred in <<art63,Article 63>>
. If there has already been an impact assessment in the context of the adoption carried out by the Union or their member states, and a law regulates this, <<art6,Article 6(1) (c/e)>>the above can be disregarded.
. There should be reviews carried out by the controller, especially when the risks change.

[#art36]
== Article 36: Prior consultation

. If a <<art35,data protection impact assessment>> results in a high risk if no measures are taken, the controller should consult supervisory authority
. If the supervisory authority decides that the processing infringes this Regulation, especially when the risk has not been evaluated sufficiently, the supervisory authority has 8 weeks for consultation, provide written advice to the controller (and processor if applicable) and may use any of its <<art58,powers>>. If the case is complexer the period may be extended by up to 6 weeks, the controller/processor shall be informed of this extension after a month of receipt, including a reason for the delay. These periods may be suspended until the authority has obtained information it has requested for the consulation.
. The controller must provide the authority with:
.. Where applicable: The responsibilities of controller, joint controllers, processors involved in processing - in particular for processing within a group of undertakings
.. The purposes and means of the intended processing
.. The measures and safeguards for data protection
.. Where applicable: Contact  of the data protection officer.
.. The <<art35,data protection impact assessment provided>>
.. Any other requested information
. Member States should consult the supervisory authority if they prepare legislative measures to be adopted by national government
. In case of data processing in relation to social protection and public health notwithstanding paragraph 1, controllers may be required to consult supervisory authority.

[#art37]
== Article 37: Designation of the data protection officer

The controller and processor must designate a data protection officer whenever:

. processing is carried out by a public authority, excepting courts acting in their judicial capacity
. the core activities of the controller or processor consist of *large-scale processing operations* which require regular and systematic monitoring, or of processing of <<art9, special categories>> of personal data or <<art10,data relating to criminal convictions and offenses>>.

A <<group-of-undertakings,group of undertakings>> may appoint a single data protection officer, provided that they are *easily accessible from each establishment*; in the case of a public authority, a single data protection officer may likewise be designated for several such authorities.

Controllers, processors, and their respective representatives _may_ designate data protection officers *even if not otherwise required*.

The data protection officer is designated on the basis of *professional qualities and expert knowledge of data protection law and practices* and the ability to perform the tasks specified by <<art39,Article 39>>. They may be a staff member of the controller or processor, or of an external entity bound by a service contract. *The identity of the data protection officer must be published* and provided to the <<supervisory-authority,supervisory authority>>.

[#art38]
== Article 38: Position of the data protection officer

The data protection officer is to be properly *involved in all issues* related to the protection of personal data; the controller and processor are to support them in performing their <<art39,tasks>> and maintaining their expert knowledge by *providing necessary resources*, and must ensure that any extracurricular activities carried out by the data protection officer *do not result in a conflict of interest*.

Data protection officers must report directly to the highest level of management of the controller or processor and *may not be dismissed or penalized for performing their tasks* and *may not receive instructions* regarding the completion of their tasks, and are *bound by confidentiality* in accordance with European Union or Member State law.

Data subjects may contact the data protection officer directly *regarding all issues related to the processing of their personal data and their rights* under the GDPR.

[#art39]
== Article 39: Tasks of the data protection officer

Data protection officers must have at least the following tasks:

. advising the controller and/or processor and any relevant employees of said entities
. advising the controller and/or processor regarding the data protection impact assessment in accordance with <<art35,Article 35>>
. *monitoring compliance with the GDPR*, with other European Union or Member State data protection laws, and with the policies of the controller and/or processor
. cooperating with and *acting as the contact point* for the <<supervisory-authority,supervisory authority>> on issues related to processing (see <<art36,Article 36>>) or regarding any other appropriate matter

Data protection officers should *take into account any possible risk associated with data processing* while fulfilling their obligations.

[#art40]
== Article 40: Codes of conduct

. The Member States, the supervisory authorities, the Board and the Commission shall encourage a proper code of conduct with proper application taking account the size of the enterprise.
. Controllers and processors (or their representatives) may prepare codes of conduct, amend or extend such codes. This should include:
.. fair and transparent processing
.. the legitimate interests pursue by controllers in specific contexts
.. the collection of personal data
.. the pseudonymisation of personal data
.. the information provided to the publich and to the data subjects
.. the exercise of the rights of data subjects
.. the handling of children in terms of data protection and information
.. the measures and procedures referred to in <<art24,Article 24>> and <<art25,Article 25>> and the measures to ensure security of processing referred to in <<art32,Article 32>>
.. the notification of data breaches to supervisory authorities and data subjects
.. the transfer of personal data to third countries or international organisations
.. dispute resolution procedures between controllers and data subjects with regard to processing, without prejudice of data subjects pursuant to <<art 77,Article 77>> and <<art79,Article79>>.
. In addition to adherence by controllers or processors subject to this Regulation, also controllers and processors which are not part of <<art3,Article 3>> may adhere to provider proper safeguards within the framework of personal data transfers to third countries or international organisations under the terms referred to in point (e) of <<art 46,Article 46(2)>>. Those controllers should make bindings and commitments, via contractual or other legally binding instruments to apply those safeguards.
. A code of conduct should include mechanisms which enable <<art41,the body>> to carry out mandatory monitoring by the controllers or processors, without prejucide to the tasks and powers of supervisory authorities <<art55,Article 55>>, <<art56,Article 56>>
. Associations and other bodies which intend to edit or extend the code of conduct shall send it to the supervisory authority <<art55,Article 55>>, which them approves the changes if it provides sufficient safeguards.
. Where the code of conduct (original or changed) do not relate to processing in several Member States, the supervisory authority shall register and publish the code.
. If the processing extends into several Member States the supervisory authority has to send the code of conduct to the Board <<art63,Article63>> which provides opinion whether the code provides appropriate safeguards, according to paragraph 3.
. If the board confirms that appropriate safeguards are given the opinion shall the submitted to the Commission.
. The Commission then decides if the code of conduct has a general validity within the Union. Those implementing acts shall be adopted in accordance with the examination procedure set out in <<art93,Article 93(2)>>.
. The Commission shall ensure appropriate publicity for approved codes
. The Board shall collate all approved codes in a register which is publicly available.

[#art41]
== Article 41: Monitoring of approved codes of conduct

_See also <<art40,Article 40>>._

. The person monitoring the code of conduct laid out in <<art40,Article 40>> should be done by a body which has an appropriate level of expertise in the subject manner. This should be done without prejudice to the asks and power of the supervisory authority under <<art57,Article 57>> and <<art58,Article58>>.
. This body should monitor only:
.. when proven the expertise regarding the subject
.. established procedures, which allows for analysis of the data at hand.
.. established procedures to help handle complaints about infringements as well as making those clear to the public
.. has proven that actions do not result in a conflict of interests.
. The supervisory authority shall submit the draft criteria for the supervising body (as mentioned in paragraph 1) to the Board taking the <<art63,consistency mechanism>> into consideration
. If this body finds infringements of the code, they are to inform the supervisory authority about any actions they have taken towards the controller or processor (suspension/exclusion from the code) and why they have.
. If the body is not operating according to the Regulation, the accreditation can be revoked by a supervisory authority.
. This Article shall not apply to processing carried out by public authorities and bodies.

[#art42]
== Article 42: Certification

. The Member States, the supervisory authorities, the Board and the Commission shall encourage certifications for excelling in data protection. The needs for medium and smaller sized enterprises should be taken into account.
. These Certifications are not bound to members within the Union and can also be given to subjects falling under <<art3,Article 3>>. _See also <<art46,Article 46(2) Point (f)>>_
. The certifications should be voluntary and transparent.
. The certification is not a reduction in responsibility. _See also <<art55,Article 55>> and <<art56,Article 56>>.
. The certification should be issued by one of the bodies from <<art43,Article 43>>, as well as supervisory authority based on criteria on the basis of <<art58,Article 58(3)>> or by the Board based on <<art63,Article 63>>. As the Board approves this may result in a common certification, the European Data Protection Seal.
. The controller or processor should provide the certification body (<<art43, Article 43>>) or supervisory authority (where applicable) when submitting to the certification mechanism, including access to all information which are needed to conduct a certification.
. Certifications are to be handed out for 3 years, renewed when conditions are met and withdrawn when they are not.
. All certification mechanisms and data protection seals/marks are to be stored in a publicly available register by the Board.

[#art43]
== Article 43: Certification bodies

_See also <<art40,Article 42>>._

=== TODO

[#art44]
== Article 44: General principle for transfers

Any transfer of personal data that is currently, or will be, undergoing processing after transfer to a third country or to an international organization *may only take place if the conditions laid down in Chapter V of the GDPR* (Articles <<art44,44>>, <<art45,45>>, <<art46,46>>, <<art47,47>>, <<art48,48>>, <<art49,49>> and <<art50,50>>) *are complied with* by the controller and processor, *including for onward transfers of personal data* from the third country or an international organization to another third country or to another internat­ional organization.

[#art45]
== Article 45: Transfers on the basis of an adequacy decision

Transfers of personal data to a third country or international organization may take place if the European Commission decides that the target entity *ensures an adequate level of protection*; if this is the case, no specific authorization is required for the transfer.

The following aspects are taken into account by the European Commission when assessing the adequacy of the provided level of protection:

. *the rule of law*, respect for human rights and freedoms
. legislation concerning *national and public security, defense, criminal law, and the access of public authorities to personal data*, including the implementation of said legislation, data protection rules, and security measures; this includes *rules for the further transfer of personal data* to another third country or international organization, as well as *data subject rights*
. the existence of any independent <<supervisory-authority,supervisory authorities>> responsible for *ensuring and enforcing compliance* with data protection rules
. any international commitments the third country or international organization has entered into, particularly those which relate to the protection of personal data

After an adequacy assessment is made, *the European Commission may declare that the third country or international organization ensures an adequate level of data protection* by passing an https://ec.europa.eu/info/law/law-making-process/adopting-eu-law/implementing-and-delegated-acts_en[implementing act];footnote:[This procedure is subject to the requirements laid down by Articles 5 and 8 of https://eur-lex.europa.eu/eli/reg/2011/182/oj[Regulation (EU) No 182/2011] ("the rules and general principles concerning mechanisms for control by Member States of the Commission’s exercise of implementing powers")] this act must provide a process of periodic review of the entity's adequacy, which must take place *at least every four years*; it may also identify a <<supervisory-authority,supervisory authority>>, if relevant. If it is found that the entity no longer provides an adequate level of data protection, the European Commission shall *repeal or amend its decision*. This _does not affect_ the transfer of data to said entity in accordance with Articles <<art46,46>>, <<art47,47>>, <<art48,48>> and <<art49,49>>.

The list of approved third countries and international organizations is published in the Official Journal of the European Union and on the website of the European Commission. footnote:[https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/adequacy-decisions_en[European Commission: Adequacy decisions]]footnote:[https://ec.europa.eu/info/law/law-topic/data-protection/international-dimension-data-protection/eu-us-data-transfers_en[European Commission: EU-US Privacy Shield]]

[#art46]
== Article 46: Transfers subject to appropriate safeguards

If no relevant <<art45,adequacy decision>> has been made, a controller or processor may only transfer personal data to a third country or international organization if said controller or processor *has provided appropriate safeguards*, and data subjects' rights are enforceable.

The appropriate safeguards may be provided for, without any requirement for authorization from a <<supervisory-authority,supervisory authority>>, by:

. an *enforceable, legally binding agreement* between public authorities
. <<art47,binding corporate rules (Article 47)>>
. <<art28-standard-clauses,standard data protection clauses>> adopted by the European Commission or by a supervisory authority
. an approved, binding and enforceable <<art40,code of conduct (Article 40)>>
. an approved, binding and enforceable <<art42,certification mechanism (Article 42)>>

*Subject to authorization from a competent <<supervisory-authority,supervisory authority>>*, appropriate safeguards may also be provided for by:

. *contractual clauses between the controller or processor and the recipient* (controller, processor or other) of the personal data in the third country or international organization
. administrative arrangements between public authorities *which include enforceable and effective data subject rights*

_See also <<art63,Article 63>>._

Authorizations by the European Commission, a Member State, or a <<supervisory-authority,supervisory authority>> remain *valid until amended, replaced or repealed*.

[#art47]
== Article 47: Binding corporate rules

=== TODO

[#art48]
== Article 48: Transfers or disclosures not authorised by Union law

Any judgement of a court or administrative authority of a third country *requiring a controller and/or processor to transfer or  disclose personal data* is only enforceable *if it is based on an international agreement*, such as a mutual legal assistance treaty, in force between said third country and the European Union or a Member State.

[#art49]
== Article 49: Derogations for specific situations

=== TODO

[#art50]
== Article 50: International cooperation for the protection of personal data

The European Commission and <<supervisory-authority,supervisory authorities>> will take appropriate steps to facilitate *international cooperation for the enforcement of data protection laws*, and provide relevant assistance and resources in such matters.

[#art51]
== Article 51: Supervisory authority

_See also <<art57,Article 57>>._

[#supervisory-authority]
supervisory authority::
an independent public authority *responsible for monitoring Regulation compliance* in order to protect the rights and freedoms of data subjects, and to *facilitate the free flow of personal data* within the European Union.

Cooperation between supervisory authorities and the European Commission is *subject to the consistency requirements* specified in Chapter VII, Section 2 of the GDPR (Articles <<art63,63>>, <<art64,64>>, <<art65,65>>, <<art66,66>>, and <<art67,67>>).

[#art52]
== Article 52: Independence

Each <<supervisory-authority,supervisory authority>> must act independently to perform its tasks; members must remain *free from external influence* and *must not seek or accept instructions* from third parties and may not engage in any occupation *incompatible with the tasks* of the supervisory authority.

Member States must ensure that supervisory authorities are provided with necessary *infrastructure and human, technical and financial resources*, as well as allocated separate, public annual budgets.

[#art53]
== Article 53: General conditions for the members of the supervisory authority

Members of a supervisory authority of a given Member State are appointed by:

. the State parliament
. the State government
. the head of State
. an independent body *authorized to do so under Member State law*

All members *must be sufficiently qualified* to perform the duties of the supervisory authority.

[#art54]
== Article 54: Rules on the establishment of the supervisory authority

Each Member State must, *by law*, provide for:

. the establishment of each supervisory authority
. necessary qualifications, rules, and procedures for the members of said supervisory authorities, including any applicable term limits for reappointment

Members and staff of a supervisory authority are *bound by confidentiality both during and after their term of office*.

[#art55]
== Article 55: Competence

Each supervisory authority is https://en.wikipedia.org/wiki/Competent_authority[competent] to exercise, *on the territory of its own Member State*, the powers conferred on it in accordance with the GDPR.

[#art56]
== Article 56: Competence of the lead supervisory authority

CAUTION: This article does not apply *to processing _carried out by public authorities in the public interest_*, or *_to comply with legal obligations_*, as specified in Articles <<art6,6>> and <<art55,55>>.

The <<art51,supervisory authority>> of the controller or processor's <<main-establishment,main establishment>> is authorized to act as the *lead supervisory authority* for any cross-border processing carried out by said controller or processor; however, such a supervisory authority is authorized to handle filed <<art77,complaints>> *only if said note concerns the Member State in which it is established*. In such cases, the supervisory authority must inform the lead supervisory authority without delay.

Within *three weeks from the time of receipt* of a complaint, the lead supervisory authority *must decide whether it will handle the case*, taking into account the rules for cooperation specified in <<art60,Article 60>>. If it decides not to handle the case, *the supervisory authority which informed it must handle the case instead*, as specified by Articles <<art61,61>> and <<art62,62>>.

[#art57]
== Article 57: Tasks

A supervisory authority is, *on its territory*, obligated to, among others:

. monitor and enforce GDPR compliance
. *advise national institutions and bodies* on relevant legislative and administrative measures
. *handle and investigate complaints* filed by data subjects or other entities in accordance with Articles <<art77,77>> and <<art80,80>>
. cooperate with, and provide information an assistance to, other supervisory authorities
. *provide information to data subjects*, concerning their rights under the GDPR, by request
. make controllers and/or processors aware of their obligations under the GDPR
. promote *public awareness and understanding of data protection rights*, especially to children
. adopt and authorize <<art28-standard-clauses,standard contractual clauses>> (see also <<art46,Article 46>>)
. approve <<art47,binding corporate rules>>
. maintain *a list of requirements* for <<art35,data protection impact assessments>>
. *keep record of infringements of the Regulation* (see also <<art58,Article 58>>)

Supervisory authorities *must provide a method by which <<art77,complaints can be submitted>>*, e.g. an electronic complains submission form.

The tasks of a supervisory authority must be *carried out free of charge* for the data subject and <<art37,data protection officer>>; they may nonetheless charge *a reasonable fee* if the requests are demonstrated to be manifestly *unfounded or excessive*.

[#art58]
== Article 58: Powers

Supervisory authorities have *the following powers*:

. to order the controller and/or processor and their respective representative(s) *to provide any required information*, including *access to all required personal data* and *to all premises and processing equipment* of the controller and/or processor
. to carry out *data protection audits* and review <<art42,data protection certification mechanisms>>
. to *notify the controller or processor* of an alleged infringement of the Regulation, or to issue warnings to such entities that *intended processing is likely to infringe upon the GDPR*, or to take appropriate corrective action
. to order the controller or processor *to comply with a data subject's requests* to exercise their data rights
. to order the controller or processor to *bring processing operations into Regulation compliance* within a specified time period
. to order the controller to inform the data subject of a personal data breach (see <<art33,Article 33>>)
. to impose *a restriction or ban on processing* or <<art44,*transfer of personal data to a third country* or international organization>>
. to order the *<<art16,rectification>>, <<art17,erasure>>, or <<art18,restriction of processing>>* of personal data in accordance with <<art19,Article 19>>
. to issue <<art42,certifications>> and accredit <<art43,certification bodies>>
. to order withdrawal of a certification (see Articles <<art42,42>> and <<art43,43>>)
. to impose <<art83,an administrative fine>>
. to adopt <<art28-standard-clauses,standard data protection clauses>> and authorize <<art46,contractual clauses>>
. to authorize _administrative arrangements_, as specified in <<art46,Article 46>>
. to advise the controller (see <<art36,Article 36>>)
. *to issue opinions to the public and to national authorities* and bodies, in accordance with Member State law, on any issue related to data protection
. to approve <<art47,binding corporate rules>>

Supervisory authorities must be given the power to *bring infringements of the Regulation to the attention of judicial authorities,* and, if necessary for enforcement, to engage in legal proceedings.

Member State law *may grant additional powers* to its respective supervisory authority (see <<art90,Article 90>>).

[#art59]
== Article 59: Activity reports

A supervisory authority *must compile annual reports of its activities*, to be made public and transmitted to national authorities as designated by Member State law.

[#art60]
== Article 60: Cooperation between the lead supervisory authority and the other supervisory authorities concerned

_See also <<art61,Article 61>>._

The *<<art56,lead supervisory authority>>* must cooperate with other supervisory authorities *in order to reach consensus*, and may request assistance from them in accordance with Articles <<art61,61>> and <<art62,62>>, in particular for the purpose of *monitoring or investigation of a controller or processor* established in another Member State; the <<#supervisory-authority-concerned,supervisory authorities concerned>> must *exchange all relevant information* with each other without delay.

If any of the other supervisory authorities concerned expresses a *relevant and reasoned objection* to a draft decision, the lead supervisory authority must:

. if it accepts the objection, submit a revised draft decision *within 2 weeks*
. otherwise, *it may* <<art64,*request examination* by the European Data Protection Board>> as specified in Articles <<art63,63>>, <<art64,64>> and <<art65,65>>

Otherwise, all involved supervisory authorities *are considered in agreement* with the draft decision and are bound by it; the decision is then adopted by the lead supervisory authority.

<<art68,The Board>> and other supervisory authorities *must be informed of any adopted or rejected decisions*, as well as provided *a summary of the relevant information*. After being notified of a decision, the controller and/or processor must ensure that it fully complies with said decision, and *inform the supervisory authority of all tasks it has taken* to comply.

_See also <<art66,Article 66>>_.

[#art61]
== Article 61: Mutual assistance

Supervisory authorities shall *assist and provide all relevant information* to each other (see <<art63,Chapter VII, Section 2>>); requests for assistance *must contain all necessary information*, including the purpose of the request. The requested supervisory authority may not decline the request, unless:

. it is not authorized to comply
. compliance with the request would violate this Regulation or European Union or Member state law

The requested supervisory authority *must respond to the request* and, if it refuses to comply, *must provide reasons for said refusal*.

Supervisory authorities *may not charge a few for any action taken* as part of a request for mutual assistance, unless both parties have agreed on compensation.

[#art62]
== Article 62: Joint operations of supervisory authorities

Supervisory authorities may *conduct joint operations*, including _joint investigations_ and _enforcement measures_ in which *members or staff of other Member States' supervisory authorities* are involved; in cases where a controller or processor has *establishments in multiple Member States*, or data subjects in multiple Member States are likely to be *significantly affected by data processing*, the supervisory authorities of each of those Member States have the right to *participate in joint operations*.

The host supervisory authority *may additionally confer powers* on any other involved supervisory authorities' members or staff involved in joint operations.footnote:[This process must first be authorized by the seconding supervisory authority.]

The seconding supervisory authority's members are *subject to the Member State law of the host supervisory authority*. The host Member State assumes responsibility for the actions of said members and *is liable for any damage caused by them as part of their operations*; the Member State of the seconding supervisory authority *must reimburse any sums it has paid* to persons entitled on its behalf.

_See also <<art66,Article 66>>_.

[#art63]
== Article 63: Consistency mechanism

In order to ensure the consistent application of the GDPR, supervisory authorities must cooperate with each other as necessary.

[#art64]
== Article 64: Opinion of the Board

_See also <<art68,Article 68>>._

=== TODO

[#art65]
== Article 65: Dispute resolution by the Board

_See also <<art68,Article 68>>._

The Board may adopt a *binding decision by two-thirds supermajority* of its members when:

. a <<supervisory-authority-concerned,supervisory authority concerned>> has raised an objection to a <<art60,draft decision>> by the lead supervisory authority
. there are conflicting views on which supervisory authority concerned is competent for the <<main-establishment,main establishment>>
. a competent supervisory authority does not request or follow the <<art64,opinion of the Board>>; the European Commission or any supervisory authority concerned may inform the Board of such matters

Such binding decisions must be relayed to the European Commission and published on the website of the Board, and must be adopted within one month;footnote:[This can be extended by a further month by request if the subject matter is deemed sufficiently complex.] *they are binding on the lead supervisory authority and all supervisory authorities concerned*.

[#art66]
== Article 66: Urgency procedure

If a <<supervisory-authority-concerned,supervisory authority concerned>> considers that there is *an urgent need to act* to protect data subjects' rights, it may immediately adopt provisional measures on its own territory for a time period of *no longer than three months*; <<art68,the Board>> and the European Commission must be informed of such an act without delay. If the supervisory authority believes that said measures need to urgently be finalized, it may request an *urgent opinion* or *urgent binding decision* from the Board.

The Board may approve said urgent opinion or binding decision by a simple majority of its members.

[#art67]
== Article 67: Exchange of information

The European Commission may adopt general implementing acts in order to specify conditions for the exchange of information between <<art51,supervisory authorities>> and between <<art51,supervisory authorities>> and <<art68,the Board>>.

[#art68]
== Article 68: European Data Protection Board

This article *establishes the European Data Protection Board* as a body of the European Union.

The Board:

. is represented by <<art73,its Chair>>
. is composed of *the head of one supervisory authority from each Member State*, and of the European Data Protection Supervisor, or of their respective representatives; if multiple supervisory authorities are responsible for monitoring Regulation compliance in a given Member State, they may *appoint a joint representative*

The European Commission *has the right to participate in Board activities* by means of an appointed representative, without voting rights. The European Data Protection Supervisor has voting rights *only on decisions which concern principles and rules applicable to Regulation-relevant European Union institutions*, bodies, offices and agencies.

[#art69]
== Article 69: Independence

The Board *must act independently* when performing its tasks or exercising its powers, and *shall neither seek nor take instructions* from a third party.

[#art70]
== Article 70: Tasks of the Board

_See also <<art68,Article 68>>._

The Board must ensure the consistent application of the GDPR, and shall:

. advise the European Commission on issues related to personal data protection, and on procedures for the exchange of information between controllers, processors and <<art51,supervisory authorities>> for <<art47,binding corporate rules>>
. *provide an opinion on <<art45,adequacy decisions>>*; the European Commission must provide the Board with all necessary resources for this task
. *maintain a public register of decisions taken by supervisory authorities and courts* on issues of consistency (see Articles <<art63,63>>, <<art64,64>>, <<art65,65>>, <<art66,66>> and <<art67,67>>)
. provide an opinion on <<art60, draft decisions of supervisory authorities>> in accordance with Articles <<art64,64>>, <<art65,65>> and <<art66,66>>
. *issue guidelines and recommendations* on:
.. procedures for removal of personal data (see also <<art17,Right to erasure>>)
.. criteria and conditions for <<art22,profiling>>
.. <<art34,handling personal data breaches>>, including *determination of what constitutes an "undue delay"* as specified in <<art33,Article 33>>
.. data transfers *based on <<art47,binding corporate rules>>*, see also further criteria specified by <<art49,Article 49>>
.. the setting of <<art83,administrative fines>>
.. *common procedures for reporting infringements* of the Regulation
.. creation of <<art40,common codes of conduct>> and <<art42,certification mechanisms>> (see also <<art43,Article 43>>)
.. the standardized *icons* referred to in <<art12,Article 12>>
. promote the cooperation and exchange of information and best practices between supervisory authorities

The Board must make public and forward its opinions and guidelines to the European Commission and to the <<art93,committee>>.

[#art71]
== Article 71: Reports

_See also <<art68,Article 68>>._

The Board must *prepare an annual report regarding the protection of the personal data of natural persons within the European Union* and in any relevant third countries or international organizations; this report must include a review of the application of the guidelines laid down by <<art70,Article 70>> and of any *binding decisions* made in accordance with <<art65,Article 65>>.

[#art72]
== Article 72: Procedure

Board decisions are *approved by a simple majority* unless otherwise specified; board *rules of procedure are adopted by a two-thirds supermajority* of its members.

[#art73]
== Article 73: Chair

. The Board *elects a chair* and *two deputy chairs* from amongst its members *by simple majority*.
. The position of Chair has *a term limit of five years*, renewable once.

[#art74]
== Article 74: Tasks of the Chair

_See also: <<art73,Article 73>>._

The Chair has the following tasks:

. to *convene of Board meetings* and the preparation of its agenda
. to *notify the <<art56,lead supervisory authority>>* of decisions adopted by the Board
. to ensure the *timely performance of tasks* (see also <<art63,Article 63>>)

The Board shall specify in its <<art72,rules of procedure>> the distribution of tasks between the Chair and deputy chairs.

[#art75]
== Article 75: Secretariat

The Board must have a *secretariat* provided to it by the European Data Protection Supervisor, which is responsible for the following:

. analytical, administrative and logistical support
. day-to-day business of the Board; this includes the preparation and follow-up of meetings and the *preparation and publication of opinions and decisions* adopted by the Board
. *communication between the members of the Board, <<art74,the Chair>>, and the European Commission*, and with other institutions and the public
. the translation of relevant information

[#art76]
== Article 76: Confidentiality

Board discussions *may be made confidential by the Board* if deemed necessary. Access to Board documents is governed by https://eur-lex.europa.eu/eli/reg/2001/1049/oj[Regulation (EC) No 1049/2001].

[#art77]
== Article 77: Right to lodge a complaint with a supervisory authority

Data subjects have the right to *file a complaint with a <<art51,supervisory authority>>* in the Member State of their *residence, place of work, or place of the alleged infringement*; said supervisory authority must inform the complainant of *the progress and outcome of the complaint* (see <<art78,Article 78>>).

[#art78]
== Article 78: Right to an effective judicial remedy against a supervisory authority

All natural or legal persons have *the right to an effective judicial remedy* against a legally binding decision concerning them made by a <<art51,supervisory authority>>, or when the _competent_ (see Articles <<art55,55>> and <<art56,56>>) supervisory authority *does not handle a filed complaint*, or *does not inform the data subject of the progress* and/or outcome of a filed complaint in accordance with <<art77,Article 77>>.

Proceedings against a supervisory authority *must be brought before the courts of the Member State* in which the supervisory authority is <<art3,established>>.

[#art79]
== Article 79: Right to an effective judicial remedy against a controller or processor

_See also <<art77,Article 77>>._

All natural or legal persons have *the right to an effective judicial remedy* against a controller or processor *when their rights have been infringed upon* as a result of non-Regulation-compliant processing.

Proceedings against a supervisory authority *must be brought before the courts of a Member State* in which the controller or processor has an establishment, or of the Member State of *the data subject's residence*, *unless the controller or processor is a public authority* acting in the exercise of its public powers.

[#art80]
== Article 80: Representation of data subjects

Data subjects have the right to mandate a non-profit organization to file a complaint on their behalf, provided that said organization:

. has been *properly constituted*
. has *statutory objectives* which are in the public interest
. is active in the field of data rights protection

_See also Articles <<art77,77>>, <<art78,78>>, <<art79,79>> and <<art82,82>>._

[#art81]
== Article 81: Suspension of proceedings

If multiple competent courts have information on proceedings, concerning the same subject matter and regarding processing by the same controller or processor, *all except the court first seized may suspend proceedings*; they may also *decline jurisdiction in favor of the court first seized*, if that court has jurisdiction over said proceedings.

[quote,Recital 144]
Proceedings are deemed to be related where they are so closely connected that it is expedient to hear and determine them together in order to avoid the risk of irreconcilable judgments resulting from separate proceedings.

[#art82]
== Article 82: Right to compensation and liability

Any person who has suffered as a result of an infringement of the GDPR *has the right to receive compensation* from the controller or processor; processors are only liable for any damage caused if it has not complied with elements of the GDPR that specifically target processors, or if it has acted *without proper authorization from the controller*.

If multiple controllers or processors are involved in the same processing and are responsible for any damage caused, *they must all be held liable* for said damage; each controller or processor is entitled to claim back their part of the compensation from the other controllers or processors involved.

[#art83]
== Article 83: General conditions for imposing administrative fines

<<art51,Supervisory authorities>> must  ensure that any *administrative fines* imposed for infringements of the GDPR are considered *effective, proportionate and dissuasive*.

When deciding whether to impose an administrative fine, the supervisory authority must take into account:

. the nature, scope or purpose of the processing, the number of data subjects affected, and the level of damage caused
. any action taken by the controller or processor to mitigate the damage
. the *degree of responsibility of the controller or processor*, taking into account measures implemented by them in accordance with Articles <<art25,25>> and <<art32,32>>
. *any previous infringements* by the controller or processor
. any cooperation with the supervisory authority to mitigate the damage
. the categories of affected personal data
. *the manner in which the infringement became known*
. *previous compliance with supervisory powers specified in <<art58,Article 58>>*
. adherence to <<art40,approved codes of conduct>> or <<art42,approved certification mechanisms>>
. any other relevant factors

Infringements of the following provisions are subject to administrative fines of *the greater of ten million Euro and 2% of the total worldwide annual turnover of the preceding year*, if applicable:

. the basic obligations of the controller or processor (see Articles <<art8,8>>, <<art11,11>>, <<art25,25>>, <<art26,26>>, <<art27,27>>, <<art28,28>>, <<art29,29>>, <<art30,30>>, <<art31,31>>, <<art32,32>>, <<art33,33>>, <<art34,34>>, <<art35,35>>, <<art36,36>>, <<art37,37>>, <<art38,38>>, <<art39,39>>, <<art42,42>> and <<art43,43>>)
. the obligations of the certification body (see Articles <<art42,42>> and <<art43,43>>)
. the obligations of the monitoring body (see <<art41,Article 41>>)

Infringements of the following provisions are subject to administrative fines of *the greater of twenty million Euro and 4% of the total worldwide annual turnover of the preceding year*, if applicable:

. *basic principles for processing*, including conditions for consent (see Articles <<art5,5>>, <<art6,6>>, <<art7,7>> and <<art9,9>>)
. data subjects' rights (see Articles <<art12,12>>, <<art13,13>>, <<art14,14>>, <<art15,15>>, <<art16,16>>, <<art17,17>>, <<art18,18>>, <<art19,19>>, <<art20,20>>, <<art21,21>> and <<art22,22>>)
. transfers of personal data to a third country or international organization (see Articles <<art44,44>>, <<art45,45>>, <<art46,46>>, <<art47,47>>, <<art48,48>> and <<art49,49>>)
. compliance with an order to limit processing, to suspend the flow of data to a third country or international organization or to provide access (see <<art58,Article 58>>)
. other relevant Member State laws

Non-compliance with <<art58,an order by a supervisory authority>> is subject to administrative fines of *the greater of twenty million euro and 4% of the total worldwide annual turnover of the preceding year*, if applicable.

[#art84]
== Article 84: Penalties

_See also: <<art83,Article 83>>._

Member States must specify relevant rules for other *effective, proportionate and dissuasive penalties* applicable to infringements of the GDPR, in particular for infringements which are not subject to <<art83,administrative fines>>, and must take necessary measures to *ensure that they are implemented*; the European Commission *must be informed of such laws by 25 May 2018*, and of any subsequent amendments.

[#art85]
== Article 85: Processing and freedom of expression and information

Member States must by law ensure that the right to the protection of personal data *is compatible with the right to freedom of expression and information*; this includes processing for *journalistic, academic, artistic and literary* purposes, for which Member States must provide *exemptions from Chapters II-VII and IX of the GDPR if they are necessary to ensure the aforementioned compatibility* (see Articles <<art5,5>>, <<art6,6>>, <<art7,7>>, <<art8,8>>, <<art9,9>>, <<art10,10>>, <<art11,11>>, <<art12,12>>, <<art13,13>>, <<art14,14>>, <<art15,15>>, <<art16,16>>, <<art17,17>>, <<art18,18>>, <<art19,19>>, <<art20,20>>, <<art21,21>>, <<art22,22>>, <<art23,23>>, <<art24,24>>, <<art25,25>>, <<art26,26>>, <<art27,27>>, <<art28,28>>, <<art29,29>>, <<art30,30>>, <<art31,31>>, <<art32,32>>, <<art33,33>>, <<art34,34>>, <<art35,35>>, <<art36,36>>, <<art37,37>>, <<art38,38>>, <<art39,39>>, <<art40,40>>, <<art41,41>>, <<art42,42>>, <<art43,43>>, <<art44,44>>, <<art45,45>>, <<art46,46>>, <<art47,47>>, <<art48,48>>, <<art49,49>>, <<art50,50>>, <<art51,51>>, <<art52,52>>, <<art53,53>>, <<art54,54>>, <<art55,55>>, <<art56,56>>, <<art57,57>>, <<art58,58>>, <<art59,59>>, <<art60,60>>, <<art61,61>>, <<art62,62>>, <<art63,63>>, <<art64,64>>, <<art65,65>>, <<art66,66>>, <<art67,67>>, <<art68,68>>, <<art69,69>>, <<art70,70>>, <<art71,71>>, <<art72,72>>, <<art73,73>>, <<art74,74>>, <<art75,75>>, <<art76,76>>, <<art85,85>>, <<art86,86>>, <<art87,87>>, <<art88,88>>, <<art89,89>>, <<art90,90>> and <<art91,91>>).

[#art86]
== Article 86: Processing and public access to official documents

Personal data in official documents help by a public body, or by a private body for the performance of a task in the public interest, *may be disclosed by said body* in accordance with European Union or Member State law, in order to <<art85,reconcile>> public access to official documents with the right to data protection.

[#art87]
== Article 87: Processing of the national identification number

Member States may determine further special conditions for the processing, with the appropriate privacy safeguards, of a *national identification number* or of any other generally-appliable identifier.

[#art88]
== Article 88: Processing in the context of employment

Member States may provide more specific rules to ensure the protection of the rights and freedoms with respect to *the processing of employees' personal data* in the context of their employment, in particular for the purposes of recruitment or the performance of the contract of employment, including:

. equality and diversity
. health and safety,
. protection of an employer's or customer's property,
. protection of employees' rights
. *termination of employment*.

These rules must include *suitable measures to safeguard the data subject's rights*, particularly regarding <<art12,transparency>> of processing and transfers of personal data within a <<group-of-undertakings,group of undertakings>>.

[#art89]
== Article 89: Safeguards and derogations relating to processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes

Processing for archiving purposes in the public interest or for research purposes *must be subject to appropriate privacy safeguards*, including but not limited to <<pseudonymization,pseudonymization>> and <<art5,data minimization>> (see also <<art25,Article 25>>); European Union or Member State law may provide certain exceptions to these rules if they are likely to *impair or render impossible the fulfillment* of the specified purpose.

[#art90]
== Article 90: Obligations of secrecy

Member States may introduce specific rules to *further specify the powers of <<art51,supervisory authorities>>*, as specified in <<art58,Article 58>> regarding controllers or processors that are *subject to an obligation of secrecy* and the data received as part of an activity covered by said obligation.

[#art91]
== Article 91: Existing data protection rules of churches and religious associations

Data protection rules applied by *churches or religious organizations* in a Member State may continue to apply, *provided that they are brought into line* with the GDPR; said associations are subject to the supervision of an *independent supervisory authority* as specified by Chapter VI of the Regulation (see Articles <<art51,51>>, <<art52,52>>, <<art53,53>>, <<art54,54>>, <<art55,55>>, <<art56,56>>, <<art57,57>>, <<art58,58>> and <<art59,59>>).

[#art92]
== Article 92: Exercise of the delegation

Starting on 24 May 2016 the European Commission will be given the power to adopt *delegated acts* (see Articles <<art12,12>> and <<art43,43>>) from 24 May 2016 onwards; this power *may be revoked at any time* by the European Parliament or Council of the European Union, in which case *the validity of any existing delegated acts is not affected*.

Delegated acts may only enter into force if *neither the European Parliament nor Council of the European Union have objected* to said act *within three months* from the notification of the act to the Parliament and the Council, or if the Parliament and Council have both informed the European Commission that they will not object.

[#art93]
== Article 93: Committee procedure

The European Commission shall be assisted by a committee, as specified by https://eur-lex.europa.eu/eli/reg/2011/182/oj[Regulation (EU) No 182/2011].

[#art94]
== Article 94: Repeal of Directive 95/46/EC

*Starting on 25 May 2018*, the *1995 Data Protection Directive* (https://eur-lex.europa.eu/eli/dir/1995/46/oj[Directive 95/46/EC]) is no longer in effect. References to said Directive are to be interpreted as references to the GDPR; the *Working Party on the Protection of Individuals* as specified by Article 29 of the Directive has been effectively replaced by the <<art68,European Data Protection Board>>.

[#art95]
== Article 95: Relationship with Directive 2002/58/EC

_See also: https://eur-lex.europa.eu/eli/dir/2002/58/2009-12-19[Privacy and Electronic Communications Directive (Directive 2002/58/EC)]._

[#art96]
== Article 96: Relationship with previously concluded Agreements

[quote,Article 96]
International agreements involving the transfer of personal data to third countries or international organisations which were concluded by Member States prior to 24 May 2016, and which comply with Union law as applicable prior to that date, shall remain in force until amended, replaced or revoked.

[#art97]
== Article 97: Commission reports

By 25 May 2020, and every four years afterwards, the European Commission must *submit and make public* a report on *the evaluation and review of the GDPR* to the European Parliament and the Council of the European Union.

In particular, the European Commission must examine:

. the application of Chapter V regarding the transfer of personal to third countries or international organizations (see Articles <<art44,44>>, <<art45,45>>, <<art46,46>>, <<art47,47>>, <<art48,48>>, <<art49,49>> and <<art50,50>>)
. the application of Chapter VII regarding cooperation and consistency (see Articles <<art60,60>>, <<art61,61>>, <<art62,62>>, <<art63,63>>, <<art64,64>>, <<art65,65>>, <<art66,66>> and <<art67,67>>)

[#art98]
== Article 98: Review of other Union legal acts on data protection

[quote,Article 98]
The Commission shall, if appropriate, submit legislative proposals with a view to amending other Union legal acts on the protection of personal data, *in order to ensure uniform and consistent protection of natural persons* with regard to processing. This shall in particular concern the rules relating to the protection of  natural persons with regard to processing by Union institutions, bodies, offices and agencies and on the free movement of such data.

[#art99]
== Article 99: Entry into force and application

*The GDPR enters into force on 25 May 2018*.
