:toc:
:toclevels: 5

= General Data Protection Regulation

Source: https://eur-lex.europa.eu/eli/reg/2016/679/oj[eur-lex.europa.eu]

[quote]
Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural
persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive
95/46/EC (General Data Protection Regulation)

[#art1]
== Article 1: Subject matter and objectives

The GDPR regulates the fundamental rights of *natural persons* regarding the protection and free movement of
*personal data* throughout the European Union and European Economic Area.

[#art2]
== Article 2: Material scope

The GDPR applies to the *wholly or partly automated processing* of personal data,
and to the *manual processing* of personal data that is part of a <<art4,*filing system* (Article 4(6))>>.

The GDPR _does not_ apply to the processing of personal data for purposes that are:

. outside the scope of *European Union law*
. in accordance with *Chapter 2 of Title V of the
https://eur-lex.europa.eu/eli/treaty/teu_2012/oj[Treaty on European Union]*
(General provisions on the Union's external action and specific provisions on the common foreign and security policy)
. *personal/household activities* carried out by a *natural person*
. required by *competent authorities* for the investigation and prevention of *criminal offenses*
or to execute relevant penalties

The GDPR *does not affect* the application of the
https://eur-lex.europa.eu/eli/dir/2000/31/oj[2000 directive on electronic commerce]
(see Articles 12–15).

[#art3]
== Article 3: Territorial scope

The GDPR applies to:

. the processing of personal data by *controllers and processors* established in the European Union
(_cf._ <<main-establishment,main establishment>>),
*regardless of the actual location of processing*
. the processing of personal data by controllers and processors in any location where Member State law applies
. the processing of personal data of *data subjects in the European Union* by controllers and processors
established elsewhere, if:
.. goods or services are being offered
.. subjects' behavior within the European Union is otherwise being monitored

[#art4]
== Article 4: Definitions

*personal data*::
any information relating to *an <<identifiable-natural-person,_identified or identifiable_ natural person*>>
(the *data subject*)
[#identifiable-natural-person]
*identifiable natural person*::
a natural person who can be *directly or indirectly* identified through use of a name, ID, location data, or other
identifier specific to the person (see also: <<genetic-data,genetic data>>).
[#processing]
*processing*:: any operation performed on personal data, regardless of whether it is automated;
this includes collection, recording, structuring, *storage*, alteration, retrieval, and dissemination of personal data.
*restriction of processing*:: the marking of stored personal data so as to limit its future processing
*profiling*:: automated processing of personal data to evaluate personal aspects of the data subject; this includes
the analysis or prediction of the subject's performance, economic situation, health, interests, location, etc.
[#pseudonymization]
*pseudonymization*:: the processing of personal data in order to prevent identification of the respective data subject
without additional information; said additional information must be stored separately and adequately secured
*filing system*:: a structured, accessible and identifiable set of personal data
*controller*:: an entity which, alone or jointly with others, determines the *purposes and means* of the processing of
personal data
*processor*:: an entity which <<processing,processes>> personal data on behalf of a controller
*recipient*:: an entity to which personal data is provided; public authorities which receive personal data as part of
an inquiry *are not considered recipients* but must comply with applicable data protection rules
*third party*:: an entity other than the data subject, controller, or processor which is authorized to process personal
data
[#consent]
*consent*:: *freely given, specific, informed and unambiguous* indication that the data subject agrees to have their
personal data processed
*personal data breach*:: a breach of security leading to *the destruction, loss, alteration, unauthorized disclosure of or access to* processed personal data
[#genetic-data]
*genetic data*::
personal data relating to unique *inherited or acquired genetic characteristics* of a natural person,
particularly that which results from an analysis of a biological sample
*biometric data*::
personal data resulting from technical processing, relating to physical, physiological or behavioral characteristics
of a natural person; this includes facial images or fingerprints
[#main-establishment]
*main establishment* (controllers)::
the establishment of the controller in the European Union where *the decisions on the purposes and means of processing*
are made; by default, this is the place of central administration within the European Union
*main establishment* (processors)::
the establishment of the processor in the European Union where *the main processing activities* take place;
by default, this is the place of central administration within the European Union
*representative*:: a natural or legal person established in the European Union who represents (see <<art27,Article 27>>)
a controller or processor
*enterprise*:: a natural or legal person engaged in an economic activity; this includes partnerships or associations
*group of undertakings*:: a controlling *undertaking* and its controlled undertakings
footnote:[https://uk.practicallaw.thomsonreuters.com/w-014-8183[Practical Law: group of undertakings]]
*binding corporate rules*:: data protection policies which are followed by a controller or processor
established in a Member State for *transfers of personal data to a controller or processor in a third country*
within a group of undertakings.
*supervisory authority*:: see <<art51,Article 51>>
*supervisory authority concerned*::
a supervisory authority *concerned by* the processing of personal data because:

. the controller or processor is established on the territory of the supervisory authority's Member State
. data subjects in said Member State are (likely to be) substantially affected by said processing
. a complaint has been filed with the supervisory authority
*cross-border processing*:: personal data processing that involves data subjects or controllers/processors
in multiple Member States
*relevant and reasoned objection*::
an objection regarding whether the GDPR has been infringed upon
*information society service*::
a paid service provided electronically, upon request by the recipient, for the processing and storage of
data (see Article 1(1) of https://eur-lex.europa.eu/eli/dir/2015/1535/oj[Directive (EU) 2015/1535])
*international organization*::
an organization and its subordinates governed by international law

[#art5]
== Article 5: Principles relating to processing of personal data

The controller is responsible ("accountability") for ensuring that personal data is:

. *lawfully, fairly and transparently* processed ("lawfulness, fairness and transparency").
. collected for *specific, explicit and legitimate* purposes
. *relevant* and *limited* to the specified purpose ("data minimization")
. accurate and kept up to date; inaccurate personal data *must be erased or updated without delay* ("accuracy")
. suitably anonymized; data subjects *must not be identifiable for longer than necessary*
.. Personal data may be archived for longer periods *in the public interest or for research purposes*
(see <<art89,Article 89>>) with the appropriate privacy safeguards
. *appropriately secured*; this includes protection against unauthorized access and data loss, destruction or other
damage ("integrity and confidentiality")

== Article 6: Lawfulness of processing

Data processing is *lawful* if at least one of the following applies:

[#art6-consent]
. the data subject has given <<consent,consent>> to the processing of their personal data for a specific purpose
. processing is necessary to *fulfill a contract* with the data subject
. processing is *requested by the data subject* prior to entering into a contract
. processing is necessary to comply with the controller's *legal obligations*
footnoteref:[art6-2,The conditions for such processing are specified by European Union law;
Member States may introduce more specific requirements.]
. processing is necessary to protect the *vital interests of the data subject*
. processing is necessary to carry out an action *in the public interest* footnoteref:[art6-2]
. processing is necessary to *exercise an official authority* of the controller footnoteref:[art6-2]
. processing is necessary to pursue the interests of the controller or of a third party,
given that these interests do not infringe on the fundamental rights of the data subject,
*in particular, when the data subject is a child*.
.. This does not apply to processing carried out by public authorities.

If data processing occurs for purposes other than that for which the personal data was initially collected,
and *is not based on consent of the data subject* or on European Union or Member State law,
the controller *must take into account* (among other things) the following,
in order to determine whether the processing is compatible:

. any link between *the initial purpose* and the intended further processing
. the context of the data collection
. whether *"special personal data"* (see <<art9, Article 9>>) is processed
. whether personal data related to criminal convictions or offenses (see <<art10,Article 10>>) is processed
. *any possible consequences* of the intended further processing
. *any appropriate safeguards*; this includes *encryption* or *<<pseudonymization,pseudonymization>>*

[#art7]
== Article 7: Conditions for consent

If the lawfulness of data processing is *<<art6-consent,based on consent>>*,
the controller *must be able to clearly demonstrate* that the data subject has freely consented
to the processing of their personal data. Data subjects must be *clearly informed* when consent is required,
and *must be allowed to withdraw their consent* at any time;
withdrawal *must not be made any more difficult* than the initial request for consent.

Consent should not be "bundled up as a condition of service", unless it is *absolutely necessary*
footnote:[https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/consent/what-is-valid-consent[UK Information Commissioner's Office: What is valid consent?]];
if consent is required as part of the conditions for a contract, but *is not absolutely necessary* for its fulfillment,
it is not considered freely given.
