:toc:
:toclevels: 5

= General Data Protection Regulation

Source: https://eur-lex.europa.eu/eli/reg/2016/679/oj[eur-lex.europa.eu]

[quote]
Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation)

[#art1]
== Article 1: Subject matter and objectives

The GDPR regulates the fundamental rights of *natural persons* regarding the protection and free movement of *personal data* throughout the European Union and European Economic Area.

[#art2]
== Article 2: Material scope

The GDPR applies to the *wholly or partly automated processing* of personal data, and to the *manual processing* of personal data that is part of a *<<filing-system,filing system>>*.

The GDPR _does not_ apply to the processing of personal data for purposes that are:

. outside the scope of *European Union law*
. in accordance with *Chapter 2 of Title V of the https://eur-lex.europa.eu/eli/treaty/teu_2012/oj[Treaty on European Union]* (General provisions on the Union's external action and specific provisions on the common foreign and security policy)
. *personal/household activities* carried out by a *natural person*
. required by *competent authorities* for the investigation and prevention of *criminal offenses* or to execute relevant penalties

The GDPR *does not affect* the application of the https://eur-lex.europa.eu/eli/dir/2000/31/oj[2000 directive on electronic commerce] (see Articles 12–15).

[#art3]
== Article 3: Territorial scope

The GDPR applies to:

. the processing of personal data by *controllers and processors* established in the European Union (_cf._ <<main-establishment,main establishment>>), *regardless of the actual location of processing*
. the processing of personal data by controllers and processors in any location where Member State law applies
. the processing of personal data of *data subjects in the European Union* by controllers and processors established elsewhere, if:
.. goods or services are being offered
.. subjects' behavior within the European Union is otherwise being monitored

[#art4]
== Article 4: Definitions

personal data::
any information relating to *an <<identifiable-natural-person,_identified or identifiable_ natural person*>> (the *data subject*)

[#identifiable-natural-person]
identifiable natural person::
a natural person who can be *directly or indirectly* identified through use of a name, ID, location data, or other identifier specific to the person (see also: <<genetic-data,genetic data>>).

[#processing]
processing::
any operation performed on personal data, regardless of whether it is automated; this includes collection, recording, structuring, *storage*, alteration, retrieval, and dissemination of personal data.

restriction of processing::
the marking of stored personal data so as to limit its future processing

[#profiling]
profiling::
automated processing of personal data to evaluate personal aspects of the data subject; this includes the analysis or prediction of the subject's performance, economic situation, health, interests, location, etc.

[#pseudonymization]
pseudonymization::
the processing of personal data in order to prevent identification of the respective data subject without additional information; said additional information must be *stored separately and adequately secured*

[#filing-system]
filing system::
a structured, accessible and identifiable set of personal data

controller::
an entity which, alone or jointly with others, determines the *purposes and means* of the processing of personal data

processor::
an entity which <<processing,processes>> personal data on behalf of a controller

recipient::
an entity to which personal data is provided; public authorities which receive personal data as part of an inquiry *are not considered recipients* but must comply with applicable data protection rules

[#third-party]
third party::
an entity other than the data subject, controller, or processor which is authorized to process personal data

[#consent]
consent::
*freely given, specific, informed and unambiguous* indication that the data subject agrees to have their personal data processed

personal data breach::
a breach of security leading to *the destruction, loss, alteration, unauthorized disclosure of or access to* processed personal data

[#genetic-data]
genetic data::
personal data relating to unique *inherited or acquired genetic characteristics* of a natural person, particularly that which results from an analysis of a biological sample

[#biometric-data]
biometric data::
personal data resulting from technical processing, relating to physical, physiological or behavioral characteristics of a natural person; this includes facial images or fingerprints

[#main-establishment]
main establishment (controllers)::
the establishment of the controller in the European Union where *the decisions on the purposes and means of processing* are made; by default, this is the place of central administration within the European Union

main establishment (processors)::
the establishment of the processor in the European Union where *the main processing activities* take place; by default, this is the place of central administration within the European Union

representative::
a natural or legal person established in the European Union who represents (see <<art27,Article 27>>) a controller or processor

enterprise::
a natural or legal person engaged in an economic activity; this includes partnerships or associations

group of undertakings::
a controlling *undertaking* and its controlled undertakings
footnote:[https://uk.practicallaw.thomsonreuters.com/w-014-8183[Practical Law: group of undertakings]]

binding corporate rules::
data protection policies which are followed by a controller or processor established in a Member State for *transfers of personal data to a controller or processor in a third country* within a group of undertakings.

[#art4-supervisory-authority]
supervisory authority::
see <<art51,Article 51>>

supervisory authority concerned::
a supervisory authority *concerned by* the processing of personal data because:

. the controller or processor is established on the territory of the supervisory authority's Member State
. data subjects in said Member State are (likely to be) substantially affected by said processing
. a complaint has been filed with the supervisory authority

cross-border processing::
personal data processing that involves data subjects or controllers/processors in multiple Member States

relevant and reasoned objection::
an objection regarding whether the GDPR has been infringed upon

[#information-society-service]
information society service::
a paid service provided electronically, upon request by the recipient, for the processing and storage of data (see Article 1(1) of https://eur-lex.europa.eu/eli/dir/2015/1535/oj[Directive (EU) 2015/1535])

international organization::
an organization and its subordinates governed by international law

[#art5]
== Article 5: Principles relating to processing of personal data

The controller is responsible ("accountability") for ensuring that personal data is:

. *lawfully, fairly and transparently* processed ("lawfulness, fairness and transparency").
. collected for *specific, explicit and legitimate* purposes
. *relevant* and *limited* to the specified purpose ("data minimization")
. accurate and kept up to date; inaccurate personal data *must be erased or updated without delay* ("accuracy")
. suitably anonymized; data subjects *must not be identifiable for longer than necessary*
.. Personal data may be archived for longer periods *in the public interest or for research purposes* (see <<art89,Article 89>>) with the appropriate privacy safeguards
. *appropriately secured*; this includes protection against unauthorized access and data loss, destruction or other
damage ("integrity and confidentiality")

[#art6]
== Article 6: Lawfulness of processing

Data processing is *lawful* if at least one of the following applies:

. the data subject has given <<consent,consent>> to the processing of their personal data for a specific purpose
. processing is necessary to *fulfill a contract* with the data subject
. processing is *requested by the data subject* prior to entering into a contract
. processing is necessary to comply with the controller's *legal obligations* footnoteref:[art6-2,The conditions for such processing are specified by European Union law; Member States may introduce more specific requirements.]
. processing is necessary to protect the *vital interests of the data subject*
. processing is necessary to carry out an action *in the public interest* footnoteref:[art6-2]
. processing is necessary to *exercise an official authority* of the controller footnoteref:[art6-2]
[#art6-interests]
. processing is necessary to pursue the interests of the controller or of a third party, given that these interests do not infringe on the fundamental rights of the data subject, *in particular when the data subject is a child*.
.. This does not apply to processing carried out by public authorities.

If data processing occurs for purposes other than that for which the personal data was initially collected, and *is not based on consent of the data subject* or on European Union or Member State law, the controller *must take into account* (among other things) the following, in order to determine whether the processing is compatible:

. any link between *the initial purpose* and the intended further processing
. the context of the data collection
. whether *"special personal data"* (see <<art9, Article 9>>) is processed
. whether personal data related to criminal convictions or offenses (see <<art10,Article 10>>) is processed
. *any possible consequences* of the intended further processing
. *any appropriate safeguards*; this includes *encryption* or *<<pseudonymization,pseudonymization>>*

[#art7]
== Article 7: Conditions for consent

If the lawfulness of data processing is *<<art6,based on consent>>*, the controller *must be able to clearly demonstrate* that the data subject has freely consented to the processing of their personal data. Data subjects must be *clearly informed* when consent is required, and *must be allowed to withdraw their consent* at any time; withdrawal *must not be made any more difficult* than the initial request for consent.

Consent should not be "bundled up as a condition of service", unless it is *absolutely necessary* footnote:[https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/consent/what-is-valid-consent[UK Information Commissioner's Office: What is valid consent?]]; if consent is required as part of the conditions for a contract, but *is not absolutely necessary* for its fulfillment, it is *not considered freely given*.

[#art8]
== Article 8: Conditions applicable to child's consent in relation to information society services

_See also <<information-society-service,information society services>>._

If the data subject is a child, and has consented to the processing of their personal data, said processing is legal if:

. the data subject is at least 16 years old footnote:[Member States may provide lower ages, provided that said age is not below 13 years.]
. consent has been given by the child's legal guardian
.. The controller must *make reasonable efforts* to verify that any given consent has been properly authorized.

[#art9]
== Article 9: Processing of special categories of personal data

Processing of personal data concerning:

. racial or ethnic origin
. political opinions
. religious or philosophical beliefs
. trade union membership
. <<genetic-data,genetic>>, <<biometric-data,biometric>> and health data *for the purpose of identifying a natural person*
. a natural person's *sex life or sexual orientation*

*is prohibited*, unless at least one of the following applies:

[#art9-exceptions]
. the data subject has *explicitly given consent*, unless European Union or Member State law otherwise dictate that *the prohibition may not be lifted*
. processing is necessary to carry out the obligations or execute specific rights of the controller or data subject related to *employment or social security and social protection law*, provided that it is authorized by European Union or Member State law, or by a *https://en.wikipedia.org/wiki/Collective_agreement[collective agreement]* in accordance with Member State law
. processing is necessary *to protect the <<art6,vital interests>>* of the data subject
. processing is carried out, with the appropriate safeguards, *as part of a non-profit organization's legitimate activities*, provided that the processing relates *only to the current or former members* of the organization, or to members that have *regular contact* with it; personal data must not be disclosed outside the scope of said organization without the consent of the data subject
. processing relates to personal data that is *in the public domain* (has been manifestly made public by the data subject)
. processing is necessary for *the establishment, exercise or defense of legal claims*, or when a court acts in its judicial capacity
. processing is *in the public interest*, with the appropriate safeguards, in accordance with European Union or Member State law
. processing is necessary for the purposes of *preventive or occupational medicine*, provided that the professional is *subject to confidentiality* (professional secrecy) under European Union or Member State law, or *rules established by national competent bodies*
. processing is necessary for archiving or for research purposes, with the appropriate safeguards

Member States may introduce more specific restrictions regarding the processing of <<genetic-data,genetic>>, <<biometric-data,biometric>> and health data.

[#art10]
== Article 10: Processing of personal data relating to criminal convictions and offenses

Processing of personal data relating to criminal convictions and offenses may only be carried out *with the appropriate safeguards*, and must occur *under the control of an official authority*, or when it is otherwise authorized by European Union or Member State law.

[#art11]
== Article 11: Processing which does not require identification

If a controller does not require the identification of a data subject, they are *not required* to maintain or process additional information in order to identify the data subject to comply with the GDPR.

[#art11-2]
If a controller demonstrably is not in a position to be able to identify the data subject, they must attempt to inform the data subject of this; Articles <<art16,16>>, <<art17,17>>, <<art18,18>>, <<art19,19>> and <<art20,20>> do not apply in such a situation, *unless the data subject provides additional identifying information* in order to exercise their rights under said articles.

[#art12]
== Article 12: Transparent information, communication and modalities for the exercise of the rights of the data subject

All processed personal data referred to by Articles <<art13,13>>, <<art14,14>>, <<art15,15>>, <<art16,16>>, <<art17,17>>, <<art18,18>>, <<art19,19>>, <<art20,20>>, <<art21,21>>, <<art22,22>>, and <<art34,34>> must be provided (in writing, orally, or by other means) to the data subject in a *concise, transparent, intelligible and easily accessible form*, particularly for *any information addressed to a child*. Controllers must facilitate the exercise of data subjects' rights according to Articles 15–22, unless they <<art11-2,demonstrably cannot identify the data subject>>.

Controllers must provide information on the status of <<art15,requests made unter Articles 15–22>> *without undue delay*; this must occur *within one month* of the receipt of the request. If the controller does not take action, they must likewise notify the data subject within one month and inform them of the *reasons for not taking action* and of any possible *legal remedies*.

[#art12-fee]
Any information provided and actions taken under the aforementioned articles must be available *free of charge*, unless the requests are demonstrated to be manifestly *unfounded or excessive* (i.e. repetitive), the controller may charge *a reasonable fee* or refuse to act on the request. If the controller has *reasonable doubts* about the identity of the requester, they may *request additional information*.

[#art13]
== Article 13: Information to be provided where personal data are collected from the data subject

When personal data is obtained, if they have not already done so, the controller must provide the following information:

. the *identity and contact details of the controller*, and, if applicable, of its representative
. the contact details of the *<<art37,data protection officer>>*, if applicable
. the *<<art5,purposes>> and <<art6,legal basis>> of the processing*
. the *<<art6-interests,legitimate interests>>* of the controller or of a <<third-party,third party>>
. where applicable, *any intention by the controller to transfer personal data to a third country or international organisation* and of any relevant <<art45,adequacy decision>>, or in the case of transfers to which Articles <<art46,46>>, <<art47,47>> and <<art49,49>>, *a reference to the appropriate safeguards*.
. how long the personal data will be stored
. the rights of the data subject to *submit an <<art15,information>>, <<art16,rectification>> or <<art17,erasure request>>*, to *<<art18,restriction of processing>>* and *<<art20,data portability>>*,footnoteref:[ico-portability, https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/right-to-data-portability[UK Information Commissioner’s Office: Right to data portability] ] and to *withdraw consent or <<art21,object to processing>>* at any time; withdrawal of consent does not affect the lawfulness of processing prior to the withdrawal
. the right to file a complaint with a <<art4-supervisory-authority,supervisory authority>>
. *whether the acquisition of personal data is a contractual requirement*, and the consequences if it is not provided
. whether the controller intends to further process the personal data <<art5,for another purpose>>

[#art14]
== Article 14: Information to be provided where personal data have not been obtained from the data subject

When personal data has been obtained from a source other than the data subject, if they have not already done so, the controller must provide the following information:

. the *identity and contact details of the controller*, and, if applicable, of its representative
. the contact details of the *<<art37,data protection officer>>*, if applicable
. the *<<art5,purposes>> and <<art6,legal basis>> of the processing*
. the categories of the personal data
. the recipients of the personal data, if applicable
. where applicable, *any intention by the controller to transfer personal data to a third country or international organisation* and of any relevant <<art45,adequacy decision>>, or in the case of transfers to which Articles <<art46,46>>, <<art47,47>> and <<art49,49>>, *a reference to the appropriate safeguards*.
. how long the personal data will be stored
. the *<<art6-interests,legitimate interests>>* of the controller or of a <<third-party,third party>>
. the rights of the data subject to *submit an <<art15,information>>, <<art16,rectification>> or <<art17,erasure request>>*, to *<<art18,restriction of processing>>* and *<<art20,data portability>>*,footnoteref:[ico-portability]
. the right to file a complaint with a <<art4-supervisory-authority,supervisory authority>>
. *the source of the personal data*, and whether it came from publicly accessible sources
. *whether <<profiling,profiling>>, automated processing or decision-making is involved* (see Article <<art22,22>>), and, if applicable, information about its operation and possible consequences
. whether the controller intends to further process the personal data <<art5,for another purpose>>

Controllers must provide data subjects with this information *without undue delay*; this must occur *within one month* of the processing of the personal data, unless:

. informing the data subject would be *impossible, or involve a disproportionate effort*, *especially for archival or research purposes*; in these cases, the controller must ensure the data subjects' rights and freedoms are protected appropriately, including *making the information publicly available*.
. obtaining or disclosure is *explicitly laid down by European Union or Member State law*
. the personal data <<art5,must remain confidential>>

[#art15]
== Article 15: Right of access by the data subject

If requested, the controller *must inform the data subject* whether any personal data has been processed, and, if applicable, provide access to said data and the following additional information:

. the *<<art5,purpose>> of the processing*
. the categories of the personal data
. the recipients of the personal data, if applicable, especially those which are *international organizations* or are *located in third countries*
. how long the personal data will be stored
. the rights of the data subject to *submit a <<art16,rectification>> or <<art17,erasure request>>* and to *<<art18,restriction of processing>>*
. the right to file a complaint with a <<art4-supervisory-authority,supervisory authority>>
. *the source of the personal data*, and whether it came from publicly accessible sources, if <<art14,the data was not collected from the data subject>>
. *whether <<profiling,profiling>>, automated processing or decision-making is involved* (see Article <<art22,22>>), and, if applicable, information about its operation and possible consequences
. *what safeguards are in place to protect the <<art5,integrity and confidentiality>> of personal data*, if it has been transferred to a third country or to an international organization

The controller must also <<art12-fee,provide a copy of the processed personal data>>;
the right to obtain a copy *must not adversely affect the rights and freedoms of others*.

[#art16]
== Article 16: Right to rectification

The data subject has the right to request *rectification of personal data* and to *have incomplete personal data completed*, from the controller, without undue delay.

[#art17]
== Article 17: Right to erasure ("right to be forgotten")

The data subject has the right to request *erasure of personal data* from the controller without undue delay; additionally, the controller is required to erase personal data without undue delay when:

. the personal data is no longer necessary
. the data subject *withdraws consent* (see Articles <<art6,6>>, <<art9,9>> and <<art13,13>>)
. the data subject <<art21,objects to processing>>
. the personal data *has been unlawfully processed*
. the personal data must be erased to comply with European Union or Member State law

If the personal data has been made public by the controller, and is obliged by the aforementioned conditions to erase the data, the controller *must make a reasonable effort* to <<art19,inform other controllers>> which are processing said data that the data subject has requested its erasure.

These conditions *do not apply* if:

. processising is necessary to exercise *the right to freedom of expression and information*
. processing is necessary to *comply with legal obligations*, to *exercise an official authority* of the controller, or for a task *carried out in the public interest* (see <<art9-exceptions,Article 9>>)
. processing is necessary for archiving or for research purposes
. processing is necessary for *the establishment, exercise or defense of legal claims*

[#art18]
== Article 18: Restriction of processing

Restriction of processing is an alternative to <<art17,erasure>>; the data subject has the right to limit how their data is processed by requesting *restriction of processing* from the controller, provided that one of the following applies:

. the accuracy of the personal data is contested by the data subject, enabling the controller to verify its accuracy
. the processing is unlawful, but the data subject *objects to its erasure* and requests restriction of processing instead
. the personal data is no longer necessary for the controller, but it is required by the data subject for *the establishment, exercise or defense of legal claims*
. the data subject <<art21,objects to processing>>

If processing of personal data has been restricted, said data may only be processed *with the consent of the data subject*, for *the establishment, exercise or defense of legal claims*, for the protection of the rights of another natural or legal person, or for purposes that are in the public interest.

The data subject must be informed by the controller prior to the lifting of restriction of processing.

[#art19]
== Article 19: Notification obligation regarding rectification or erasure of personal data or restriction of processing

The controller must inform *all recipients of personal data* of any relevant <<art16,rectification>>, <<art17,erasure>>, or <<art18,restriction of processing>> requests made by the data subject. If the data subject requests it, they must additionally inform the data subject about said recipients.

[#art20]
== Article 20: Right to data portability

The data subject has the right to *obtain the personal data* they have provided to a controller, and have it *freely transferred to another controller*, provided that:

. the processing is <<art6,based on consent or on a contract>> to which the data subject is a party
. the data processing is automated

The right to data portability *<<art15,must not adversely affect the rights and freedoms of others>>*.

[#art21]
== Article 21: Right to object

The data subject has the right to *object to processing* which is *"carried out in the public interest" or for the purposes of the controller's legitimate interests* <<art6,as specified in Article 6>>; the controller must cease processing of personal data unless it can demonstrate *compelling legitimate grounds* for the processing which override the rights and freedoms of the data subject.

If personal data is processed for _direct marketing_, the data subject may object to processing of all related personal data, *including <<profiling,profiling>>*; the controller must then stop *all processing of said personal data* for direct marketing purposes.

If personal data is processed for *research purposes*, the data subject may object to processing unless it is a necessary task *carried out in the public interest*.

These rights must be *explicitly brought to the attention of the data subject* and must be displayed *clearly and separately* from any other information.

Data subjects may exercise their right to object by automated means (see <<information-society-service,information society services>>).

[#art22]
== Article 22: Automated individual decision-making, including profiling

The data subject has the right to not be subject to *decisions based solely on automatic processing* that significantly affect them (including <<profiling,profiling>>), unless:

. the decision is *necessary for the fulfillment of a contract* between the data subject and the controller
. the decision is *authorized by European Union or Member State law*
. the automatic processing is based on the data subject's <<art6,explicit consent>>

given that these decisions are *not based on <<art9, special categories>> of personal data* and that
*sufficient safeguards are in place* to protect the data subject's rights, freedoms and legitimate interests.

[#art23]
== Article 23: Restrictions

European Union or Member State law may restrict the scope of any obligations and rights provided by Articles <<art5,5>>, <<art12,12>>, <<art13,13>>, <<art14,14>>, <<art15,15>>, <<art16,16>>, <<art17,17>>, <<art18,18>>, <<art19,19>>, <<art20,20>>, <<art21,21>>, <<art22,22>> and <<art34,34>> when such a restriction is necessary to safeguard:

. *national and public security*
. defense
. the investigation, detection and prevention of *criminal offenses and breaches of ethics* and the execution of relevant penalties
. important objectives of *general public interest to the European Union or a Member State*; this includes, among others, economic or financial interests, public health and social security
. the *protection of judicial independence* and legal proceedings
. a regulatory function connected to an official authority
. *the protection of the data subject*, or of the rights and freedoms of others
. the enforcement of civil law claims

All such legislation must include:

. the *<<art5,purpose>> of the processing*
. the categories of the personal data
. the *scope of the introduced restrictions*
. any safeguards in place to *prevent unlawful access* to the personal data
. the specification of the controller(s)
. how long the personal data will be stored
. any risks to the rights of data subjects
. the right of data subjects to be informed about said restriction, *unless this would be detrimental to the effectiveness of the restriction*

[#art24]
== Article 24: Responsibilities of the controller

*The controller is responsible for taking steps to appropriately ensure that all processing is performed in accordance with the GDPR*; this includes the application of appropriate data protection policies.

Adherence to <<art40,approved codes of conduct>> or <<art42,approved certification mechanisms>> may be used to demonstrate Regulation compliance.

[#art25]
== Article 25: Data protection by design and by default

[quote]
____
Taking into account the state of the art, the cost of implementation and the nature, scope, context and purposes of processing as well as the risks ... for rights and freedoms of natural persons posed by the processing, *the controller shall ... implement appropriate ... measures, such as pseudonymisation, which are designed to implement data-protection principles, such as data minimisation, in an effective manner* ... in order to meet the requirements of this Regulation and protect the rights of data subjects.

The controller shall implement appropriate ... measures for ensuring that, by default, only personal data which are *necessary for each specific purpose of the processing* are processed. That obligation applies to the amount of personal data collected, the extent of their processing, the period of their storage and their accessibility. In particular, *such measures shall ensure that by default personal data are not made accessible without the individual's intervention* to an indefinite number of natural persons.
____

Approved <<art42,certification mechanisms>> may be used to demonstrate Regulation compliance.
